/*
* This file is auto-generated by AssetDump
* Do not edit manually
* Last updated: 12/18/2025 14:29:10
*/
// ReSharper disable MemberHidesStaticFromOuterClass
namespace Oxide.Ext.UiFramework.Enums;

public enum UiFont : byte
{
	NotoSansArabicBold,
	NotoSansArabicRegular,
	NotoSansHebrewBold,
	NotoEmojiRegular,
	NotoSanScjkscBold,
	RobotoRegular,
	DroidSansMono,
	Lcd,
	PermanentMarker,
	Poxel,
	PressStart2pRegular,
	RobotoCondensedBold,
	RobotoCondensedRegular,
	RobotoMonoRegular,
	SuperChiby,

}
