/*
* This file is auto-generated by AssetDump
* Do not edit manually
* Last updated: 06/07/2026 13:38:31
*/
// ReSharper disable MemberHidesStaticFromOuterClass
namespace Oxide.Ext.UiFramework.Enums;

public enum UiFont : byte
{
	NotoSansArabicBold,
	NotoSansArabicRegular,
	UniFont17003,
	NotoSansHebrewBold,
	NotoEmojiRegular,
	NotoSanScjkscBold,
	RobotoRegular,
	DroidSansMono,
	Lcd,
	PermanentMarker,
	Poxel,
	PressStart2pRegular,
	RobotoCondensedBold,
	RobotoCondensedRegular,
	RobotoMonoBold,
	RobotoMonoRegular,
	SuperChiby,

}
