/*
* This file is auto-generated by AssetDump
* Do not edit manually
* Last updated: 10/11/2025 13:39:41
*/
// ReSharper disable MemberHidesStaticFromOuterClass
namespace Oxide.Ext.UiFramework.Enums;

public enum UiLayer : byte
{
	OverlayNonScaled,
	Overlay,
	Overall,
	Hud,
	UnderNonScaled,
	Under,
	HudMenu,
	Inventory,
	TechTree,
	Crafting,
	Contacts,
	Clans,
	Map,

}
