<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <LangVersion>14</LangVersion>
        <SignAssembly>true</SignAssembly>
        <Configurations>Release;Debug</Configurations>
        <Platforms>UiFramework;Unit Tests;Benchmarks</Platforms>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|Benchmarks' ">
      <DefineConstants>TRACE;BENCHMARKS</DefineConstants>
      <Optimize>true</Optimize>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|Benchmarks' ">
      <DefineConstants>TRACE;BENCHMARKS</DefineConstants>
    </PropertyGroup>
    
    <ItemGroup>
      <Reference Include="Assembly-CSharp">
        <HintPath>..\references\Assembly-CSharp.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp-firstpass">
        <HintPath>..\references\Assembly-CSharp-firstpass.dll</HintPath>
      </Reference>
      <Reference Include="Facepunch.Console">
        <HintPath>..\..\..\OxidePlugins\OxidePlugins\References\Rust\Facepunch.Console.dll</HintPath>
      </Reference>
      <Reference Include="Facepunch.Network">
        <HintPath>..\references\Facepunch.Network.dll</HintPath>
      </Reference>
      <Reference Include="Facepunch.System">
        <HintPath>..\references\Facepunch.System.dll</HintPath>
      </Reference>
      <Reference Include="mscorlib">
        <HintPath>..\References\mscorlib.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.Common">
        <HintPath>..\References\Oxide.Common.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.Core">
        <HintPath>..\References\Oxide.Core.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.CSharp">
        <HintPath>..\references\Oxide.CSharp.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.References">
        <HintPath>..\references\Oxide.References.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.Rust">
        <HintPath>..\References\Oxide.Rust.dll</HintPath>
      </Reference>
      <Reference Include="Rust.Data">
        <HintPath>..\references\Rust.Data.dll</HintPath>
      </Reference>
      <Reference Include="System.Memory">
        <HintPath>..\references\System.Memory.dll</HintPath>
      </Reference>
      <Reference Include="System.Runtime">
        <HintPath>..\references\System.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="System.Runtime.CompilerServices.Unsafe">
        <HintPath>..\references\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine">
        <HintPath>..\references\UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>..\references\UnityEngine.CoreModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextRenderingModule">
        <HintPath>..\references\UnityEngine.TextRenderingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UI">
        <HintPath>..\references\UnityEngine.UI.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UIElementsModule">
        <HintPath>..\references\UnityEngine.UIElementsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UIModule">
        <HintPath>..\references\UnityEngine.UIModule.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Rust.UIFramework\Rust.UIFramework.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
      <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    </ItemGroup>
    
</Project>
