<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <LangVersion>14</LangVersion>
        <SignAssembly>true</SignAssembly>
        <Configurations>Release;Debug;Trace Leaks</Configurations>
        <Platforms>UiFramework;Unit Tests;Benchmarks</Platforms>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|Benchmarks' ">
      <DefineConstants>TRACE;BENCHMARKS</DefineConstants>
      <Optimize>true</Optimize>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|Benchmarks' ">
      <DefineConstants>TRACE;BENCHMARKS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Trace Leaks|Benchmarks' ">
      <DefineConstants>TRACE;BENCHMARKS</DefineConstants>
    </PropertyGroup>
    
    <ItemGroup>
      <Reference Include="Assembly-CSharp">
        <HintPath>..\References\Rust\Assembly-CSharp.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp-firstpass">
        <HintPath>..\References\Rust\Assembly-CSharp-firstpass.dll</HintPath>
      </Reference>
      <Reference Include="Facepunch.Network">
        <HintPath>..\References\Rust\Facepunch.Network.dll</HintPath>
      </Reference>
      <Reference Include="Facepunch.System">
        <HintPath>..\References\Rust\Facepunch.System.dll</HintPath>
      </Reference>
      <Reference Include="mscorlib">
        <HintPath>..\References\Rust\mscorlib.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.Common">
        <HintPath>..\References\Rust\Oxide.Common.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.Core">
        <HintPath>..\References\Rust\Oxide.Core.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.CSharp">
        <HintPath>..\References\Rust\Oxide.CSharp.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.References">
        <HintPath>..\References\Rust\Oxide.References.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.Rust">
        <HintPath>..\References\Rust\Oxide.Rust.dll</HintPath>
      </Reference>
      <Reference Include="Rust.Data">
        <HintPath>..\References\Rust\Rust.Data.dll</HintPath>
      </Reference>
      <Reference Include="System.Memory">
        <HintPath>..\References\Rust\System.Memory.dll</HintPath>
      </Reference>
      <Reference Include="System.Runtime">
        <HintPath>..\References\Rust\System.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="System.Runtime.CompilerServices.Unsafe">
        <HintPath>..\References\Rust\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine">
        <HintPath>..\References\Rust\UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>..\References\Rust\UnityEngine.CoreModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextRenderingModule">
        <HintPath>..\References\Rust\UnityEngine.TextRenderingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UI">
        <HintPath>..\References\Rust\UnityEngine.UI.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UIElementsModule">
        <HintPath>..\References\Rust\UnityEngine.UIElementsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UIModule">
        <HintPath>..\References\Rust\UnityEngine.UIModule.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Rust.UIFramework\Rust.UIFramework.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
      <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    </ItemGroup>
    
</Project>
