<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>disable</Nullable>
        <IsPackable>false</IsPackable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>14</LangVersion>
        <Configurations>Debug;Release;Trace Leaks</Configurations>
        <Platforms>Unit Tests;Benchmarks;UiFramework</Platforms>
        <TargetFramework>net9.0</TargetFramework>
        <OutputType>Library</OutputType>
        <DebugType>portable</DebugType>
        <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Argon" Version="0.34.0" />
        <PackageReference Include="coverlet.collector" Version="6.0.2"/>
        <PackageReference Include="FluentAssertions" Version="8.2.0" />
        <PackageReference Include="FluentAssertions.Analyzers" Version="0.34.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0"/>
        <PackageReference Include="Verify.XunitV3" Version="31.19.1" />
        <PackageReference Include="xunit.v3" Version="3.2.2" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
        <Using Include="FluentAssertions"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Rust.UIFramework\Rust.UIFramework.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Assembly-CSharp">
        <HintPath>..\references\Rust\Assembly-CSharp.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp-firstpass">
        <HintPath>..\references\Rust\Assembly-CSharp-firstpass.dll</HintPath>
      </Reference>
      <Reference Include="BoomlagoonJSON">
        <HintPath>..\references\Rust\BoomlagoonJSON.dll</HintPath>
      </Reference>
      <Reference Include="Facepunch.Network">
        <HintPath>..\references\Rust\Facepunch.Network.dll</HintPath>
      </Reference>
      <Reference Include="Facepunch.Unity">
        <HintPath>..\references\Rust\Facepunch.Unity.dll</HintPath>
      </Reference>
      <Reference Include="Facepunch.UnityEngine">
        <HintPath>..\references\Rust\Facepunch.UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.Core">
        <HintPath>..\references\Rust\Oxide.Core.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.CSharp">
        <HintPath>..\references\Rust\Oxide.CSharp.dll</HintPath>
      </Reference>
      <Reference Include="Rust.Global">
        <HintPath>..\references\Rust\Rust.Global.dll</HintPath>
      </Reference>
      <Reference Include="UniTask">
        <HintPath>..\references\Rust\UniTask.dll</HintPath>
      </Reference>
      <Reference Include="UniTask.Linq">
        <HintPath>..\references\Rust\UniTask.Linq.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine">
        <HintPath>..\references\Rust\UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>..\references\Rust\UnityEngine.CoreModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextRenderingModule">
        <HintPath>..\references\Rust\UnityEngine.TextRenderingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UI">
        <HintPath>..\references\Rust\UnityEngine.UI.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
