/*
* This file is auto-generated by AssetDump
* Do not edit manually
* Last updated: 06/07/2026 13:38:31
*/
// ReSharper disable MemberHidesStaticFromOuterClass
namespace Oxide.Ext.UiFramework.Constants;

public static class UiFonts
{
	public const string NotoSansArabicBold = "_nonenglish/arabic/notosansarabic-bold.ttf";
	public const string NotoSansArabicRegular = "_nonenglish/arabic/notosansarabic-regular.ttf";
	public const string UniFont17003 = "_nonenglish/currencysymbols/unifont-17.0.03.otf";
	public const string NotoSansHebrewBold = "_nonenglish/hebrew/notosanshebrew-bold.ttf";
	public const string NotoEmojiRegular = "_nonenglish/notoemoji-regular.ttf";
	public const string NotoSanScjkscBold = "_nonenglish/notosanscjksc-bold.otf";
	public const string RobotoRegular = "_roboto/roboto-regular.ttf";
	public const string DroidSansMono = "droidsansmono.ttf";
	public const string Lcd = "lcd/lcd.ttf";
	public const string PermanentMarker = "permanentmarker.ttf";
	public const string Poxel = "poxel.otf";
	public const string PressStart2pRegular = "pressstart2p-regular.ttf";
	public const string RobotoCondensedBold = "robotocondensed-bold.ttf";
	public const string RobotoCondensedRegular = "robotocondensed-regular.ttf";
	public const string RobotoMonoBold = "robotomono-bold.ttf";
	public const string RobotoMonoRegular = "robotomono-regular.ttf";
	public const string SuperChiby = "superchiby/super chiby.ttf";

}
