/*
* This file is auto-generated by AssetDump
* Do not edit manually
* Last updated: 10/11/2025 13:39:41
*/
// ReSharper disable MemberHidesStaticFromOuterClass
namespace Oxide.Ext.UiFramework.Constants;

public static class UiLayers
{
	public const string OverlayNonScaled = "OverlayNonScaled";
	public const string Overlay = "Overlay";
	public const string Overall = "Overall";
	public const string Hud = "Hud";
	public const string UnderNonScaled = "UnderNonScaled";
	public const string Under = "Under";
	public const string HudMenu = "Hud.Menu";
	public const string Inventory = "Inventory";
	public const string TechTree = "TechTree";
	public const string Crafting = "Crafting";
	public const string Contacts = "Contacts";
	public const string Clans = "Clans";
	public const string Map = "Map";

}
