/*
* This file is auto-generated by AssetDump
* Do not edit manually
* Last updated: 06/08/2026 07:33:26
*/
// ReSharper disable MemberHidesStaticFromOuterClass
namespace Oxide.Ext.UiFramework.Constants;

public static class UiTextures
{
	public static class Bundled
	{
		public static class Prefabs
		{
			public static class Fx
			{
				public static class Lightning
				{
					public const string FxLightning = "assets/bundled/prefabs/fx/lightning/fx-lightning.png";
					public const string FxLightning2 = "assets/bundled/prefabs/fx/lightning/fx-lightning2.png";
					public const string FxLightning3 = "assets/bundled/prefabs/fx/lightning/fx-lightning3.png";
					public const string FxLightning4 = "assets/bundled/prefabs/fx/lightning/fx-lightning4.png";
					public const string FxLightningTeslacoil2 = "assets/bundled/prefabs/fx/lightning/fx-lightning-teslacoil2.png";
				}
			}
			public static class Modding
			{
				public static class AssetStore
				{
					public static class BankheistPackage
					{
						public static class BankheistVol03
						{
							public static class Textures
							{
								public const string TxBankVault01aAlb = "assets/bundled/prefabs/modding/asset_store/bankheist_package/bankheist_vol03/textures/tx_bank_vault_01a_alb.png";
								public const string TxBankVault01aMs = "assets/bundled/prefabs/modding/asset_store/bankheist_package/bankheist_vol03/textures/tx_bank_vault_01a_ms.png";
								public const string TxBankVault01bAlb = "assets/bundled/prefabs/modding/asset_store/bankheist_package/bankheist_vol03/textures/tx_bank_vault_01b_alb.png";
								public const string TxBankVault01bMs = "assets/bundled/prefabs/modding/asset_store/bankheist_package/bankheist_vol03/textures/tx_bank_vault_01b_ms.png";
							}
						}
					}
				}
				public static class Cinematic
				{
					public static class Materials
					{
						public const string TrackingMarker01 = "assets/bundled/prefabs/modding/cinematic/materials/tracking_marker_01.png";
						public const string TrackingMarker02 = "assets/bundled/prefabs/modding/cinematic/materials/tracking_marker_02.png";
					}
				}
			}
			public static class Ui
			{
				public static class Menu2
				{
					public static class Assets
					{
						public const string FacepunchServerLogo = "assets/bundled/prefabs/ui/menu2/_assets/_branding/facepunch_server_logo.png";
						public const string PlaceholderWeeklySkinsBg = "assets/bundled/prefabs/ui/menu2/_assets/placeholder_weeklyskins-bg.png";
					}
					public static class Pages
					{
						public static class Store
						{
							public const string ExhibitDecorpackMediaTripod = "assets/bundled/prefabs/ui/menu2/_pages/store/general/packs/_packs/exhibit decor pack/_assets/media/exhibit_decorpack_media_tripod.jpg";

							public static class Skinviewer
							{
								public static class Models
								{
									public static class Mannequins
									{
										public static class FemaleTorso
										{
											public const string FemaleTorsoAlbedo = "assets/bundled/prefabs/ui/menu2/_pages/store/skinviewer/models/mannequins/femaletorso/femaletorso_albedo.tga";
											public const string FemaleTorsoAlbedoLight = "assets/bundled/prefabs/ui/menu2/_pages/store/skinviewer/models/mannequins/femaletorso/femaletorso_albedo_light.tga";
											public const string FemaleTorsoMetalrough = "assets/bundled/prefabs/ui/menu2/_pages/store/skinviewer/models/mannequins/femaletorso/femaletorso_metalrough.tga";
										}
										public static class FemaleTorsoLegs
										{
											public const string FemaleTorsoLegsAlbedo = "assets/bundled/prefabs/ui/menu2/_pages/store/skinviewer/models/mannequins/femaletorso_legs/femaletorso_legs_albedo.tga";
											public const string FemaleTorsoLegsAlbedoLight = "assets/bundled/prefabs/ui/menu2/_pages/store/skinviewer/models/mannequins/femaletorso_legs/femaletorso_legs_albedo-light.tga";
											public const string FemaleTorsoLegsMetalrough = "assets/bundled/prefabs/ui/menu2/_pages/store/skinviewer/models/mannequins/femaletorso_legs/femaletorso_legs_metalrough.tga";
										}
										public static class Head
										{
											public const string HeadAlbedo = "assets/bundled/prefabs/ui/menu2/_pages/store/skinviewer/models/mannequins/head/head_albedo.tga";
											public const string HeadAlbedoLight = "assets/bundled/prefabs/ui/menu2/_pages/store/skinviewer/models/mannequins/head/head_albedo_light.tga";
											public const string HeadMetalrough = "assets/bundled/prefabs/ui/menu2/_pages/store/skinviewer/models/mannequins/head/head_metalrough.tga";
										}
										public static class MaleTorso
										{
											public const string MaleTorsoAlbedo = "assets/bundled/prefabs/ui/menu2/_pages/store/skinviewer/models/mannequins/maletorso/maletorso_albedo.tga";
											public const string MaleTorsoAlbedoLight = "assets/bundled/prefabs/ui/menu2/_pages/store/skinviewer/models/mannequins/maletorso/maletorso_albedo_light.tga";
											public const string MaleTorsoMetalrough = "assets/bundled/prefabs/ui/menu2/_pages/store/skinviewer/models/mannequins/maletorso/maletorso_metalrough.tga";
										}
										public static class MaleTorsoLegs
										{
											public const string MaleTorsoLegsAlbedo = "assets/bundled/prefabs/ui/menu2/_pages/store/skinviewer/models/mannequins/maletorso_legs/maletorso_legs_albedo.tga";
											public const string MaleTorsoLegsAlbedoLight = "assets/bundled/prefabs/ui/menu2/_pages/store/skinviewer/models/mannequins/maletorso_legs/maletorso_legs_albedo_light.tga";
											public const string MaleTorsoLegsMetalrough = "assets/bundled/prefabs/ui/menu2/_pages/store/skinviewer/models/mannequins/maletorso_legs/maletorso_legs_metalrough.tga";
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	public static class Content
	{
		public const string CobaltLogistics = "assets/content/structures/coaling_tower/textures/cobalt_logistics.tga";

		public static class Building
		{
			public static class BasicGeo
			{
				public static class Materials
				{
					public const string DestroyOverlay = "assets/content/building/basicgeo/materials/destroyoverlay.tga";
					public const string Guide = "assets/content/building/basicgeo/materials/guide.tga";
					public const string GuideInvalid = "assets/content/building/basicgeo/materials/guideinvalid.tga";
					public const string LevelFrame = "assets/content/building/basicgeo/materials/levelframe.tga";
					public const string LevelMetal = "assets/content/building/basicgeo/materials/levelmetal.tga";
					public const string LevelMetalAdv = "assets/content/building/basicgeo/materials/levelmetaladv.tga";
					public const string LevelStone = "assets/content/building/basicgeo/materials/levelstone.tga";
					public const string LevelStoneAdv = "assets/content/building/basicgeo/materials/levelstoneadv.tga";
					public const string LevelWood = "assets/content/building/basicgeo/materials/levelwood.tga";
					public const string LevelWoodAdv = "assets/content/building/basicgeo/materials/levelwoodadv.tga";
				}
			}
			public static class Parts
			{
				public static class InteriorSkins
				{
					public static class Textures
					{
						public const string CarpetMask = "assets/content/building/parts/interior_skins/textures/carpet_mask.tga";
						public const string FloorCarpetABc = "assets/content/building/parts/interior_skins/textures/floor_carpet_a_bc.tga";
						public const string FloorCarpetAMg = "assets/content/building/parts/interior_skins/textures/floor_carpet_a_mg.tga";
						public const string FloorCarpetBBc = "assets/content/building/parts/interior_skins/textures/floor_carpet_b_bc.tga";
						public const string FloorCarpetCBc = "assets/content/building/parts/interior_skins/textures/floor_carpet_c_bc.tga";
					}
				}
				public static class MBoatWood
				{
					public static class Textures
					{
						public const string MboatAtlasWoodBc = "assets/content/building/parts/m_boat_wood/textures/mboat_atlas_wood_bc.tga";
						public const string MboatAtlasWoodMg = "assets/content/building/parts/m_boat_wood/textures/mboat_atlas_wood_mg.tga";
						public const string MboatWoodLodBakeLodBc = "assets/content/building/parts/m_boat_wood/textures/mboat_wood_lod_bake_lod_bc.png";
						public const string MboatWoodLodBakeLodSg = "assets/content/building/parts/m_boat_wood/textures/mboat_wood_lod_bake_lod_sg.png";
					}
				}
			}
		}

		public static class Developer
		{
			public const string DevError = "assets/content/developer/deverror.png";
			public const string DevGrey = "assets/content/developer/devgrey.png";
			public const string DevWhite = "assets/content/developer/devwhite.png";
			public const string DevWhitenobuild = "assets/content/developer/devwhitenobuild.png";
			public const string DevWhitetrigger = "assets/content/developer/devwhitetrigger.png";
		}

		public static class Effects
		{
			public const string Twinkle = "assets/content/effects/explosions/textures/twinkle.png";

			public static class Crossbreed
			{
				public const string FxCircle = "assets/content/effects/crossbreed/fx circle.png";
				public const string FxGradientSkewed = "assets/content/effects/crossbreed/fx gradient skewed.png";
			}

			public static class Textures
			{
				public static class Clouds
				{
					public const string HorizonCumulas01Bc = "assets/content/effects/textures/clouds/horizon_cumulas_01_bc.tga";
					public const string HorizonCumulas02Bc = "assets/content/effects/textures/clouds/horizon_cumulas_02_bc.tga";
					public const string HorizonCumulas03Bc = "assets/content/effects/textures/clouds/horizon_cumulas_03_bc.tga";
					public const string LargeCirrus01Bc = "assets/content/effects/textures/clouds/large_cirrus_01_bc.tga";
					public const string LargeCirrus02Bc = "assets/content/effects/textures/clouds/large_cirrus_02_bc.tga";
					public const string LargeCirrus03Bc = "assets/content/effects/textures/clouds/large_cirrus_03_bc.tga";
					public const string LargeCirrus04Bc = "assets/content/effects/textures/clouds/large_cirrus_04_bc.tga";
					public const string LargeCirrus05Bc = "assets/content/effects/textures/clouds/large_cirrus_05_bc.tga";
					public const string LargeCumulas01Bc = "assets/content/effects/textures/clouds/large_cumulas_01_bc.tga";
					public const string LargeCumulas02Bc = "assets/content/effects/textures/clouds/large_cumulas_02_bc.tga";
					public const string LargeCumulas03Bc = "assets/content/effects/textures/clouds/large_cumulas_03_bc.tga";
					public const string SingleCumulas01Bc = "assets/content/effects/textures/clouds/single_cumulas_01_bc.tga";
					public const string SingleCumulas02Bc = "assets/content/effects/textures/clouds/single_cumulas_02_bc.tga";
					public const string SingleCumulas03Bc = "assets/content/effects/textures/clouds/single_cumulas_03_bc.tga";
					public const string SingleCumulas04Bc = "assets/content/effects/textures/clouds/single_cumulas_04_bc.tga";
					public const string SingleCumulas05Bc = "assets/content/effects/textures/clouds/single_cumulas_05_bc.tga";
					public const string StratoCumulus02Bc = "assets/content/effects/textures/clouds/stratocumulus_02_bc.tga";
					public const string TransitionAltoStratus06Bc = "assets/content/effects/textures/clouds/transition_altostratus_06_bc.tga";
				}
				public static class Sand
				{
					public const string DecalParticleSoft = "assets/content/effects/textures/sand/decal_particle_soft.psd";
					public const string DecalSand2 = "assets/content/effects/textures/sand/decal_sand2.psd";
					public const string FxGradient = "assets/content/effects/textures/sand/fx_gradient.psd";
					public const string FxGradientSoftBottom = "assets/content/effects/textures/sand/fx_gradient_softbottom.psd";
					public const string SandParticleA = "assets/content/effects/textures/sand/sand_particle_a.tga";
				}
				public static class Smoke
				{
					public const string ExplosionCoreSmoke = "assets/content/effects/textures/smoke/explosion_core_smoke.png";
					public const string FrostyBreath = "assets/content/effects/textures/smoke/frosty_breath.tga";
					public const string Wispy4 = "assets/content/effects/textures/smoke/wispy-4.tga";
				}
			}
		}

		public static class Materials
		{
			public const string Cable = "assets/content/materials/cable.jpg";
			public const string HighLight = "assets/content/materials/highlight.png";
			public const string HighLight2 = "assets/content/materials/highlight2.png";
		}

		public static class Nature
		{
			public static class Terrain
			{
				public static class Misc
				{
					public const string NoisePerlin = "assets/content/nature/terrain/misc/noise_perlin.tga";
					public const string NoiseWhite = "assets/content/nature/terrain/misc/noise_white.tga";
					public const string TerrainPotatoDetail = "assets/content/nature/terrain/misc/terrain_potato_detail.png";
				}
			}
		}

		public static class Nexus
		{
			public static class Island
			{
				public const string Island1 = "assets/content/nexus/island/island.png";
				public const string Island2 = "assets/content/nexus/island/island2.png";
				public const string Island3 = "assets/content/nexus/island/island3.png";
			}
		}

		public static class Player
		{
			public static class Clothing
			{
				public const string KnittedDetailDiff = "assets/content/player/clothing/basic/materials/knitted/knitteddetail_diff.png";

				public static class TilingTextures
				{
					public const string CamoTiling01Tint = "assets/content/player/clothing/tiling_textures/camo_tiling_01_tint.tga";
					public const string CamoTilingMuricaTint = "assets/content/player/clothing/tiling_textures/camo_tiling_murica_tint.tga";
					public const string CamoTilingSovietTint = "assets/content/player/clothing/tiling_textures/camo_tiling_soviet_tint.tga";
					public const string ClothTiling01Color = "assets/content/player/clothing/tiling_textures/cloth_tiling_01_color.tga";
					public const string ClothTiling01Fuzz = "assets/content/player/clothing/tiling_textures/cloth_tiling_01_fuzz.tga";
					public const string ClothTiling02Color = "assets/content/player/clothing/tiling_textures/cloth_tiling_02_color.tga";
					public const string ClothTiling02Fuzz = "assets/content/player/clothing/tiling_textures/cloth_tiling_02_fuzz.tga";
					public const string ClothTiling03Color = "assets/content/player/clothing/tiling_textures/cloth_tiling_03_color.tga";
					public const string GenericTilingFuzz = "assets/content/player/clothing/tiling_textures/generic_tiling_fuzz.tga";
				}
			}
		}

		public static class Props
		{
			public static class LightFixtures
			{
				public static class V2
				{
					public static class Ies
					{
						public static class SpotLight
						{
							public const string IesCookieHemisphereSpot = "assets/content/props/light_fixtures/v2/ies/spotlight/ies-cookie-hemisphere-spot.tga";
							public const string IesCookieReflector1 = "assets/content/props/light_fixtures/v2/ies/spotlight/ies-cookie-reflector1.tga";
							public const string IesCookieReflector2 = "assets/content/props/light_fixtures/v2/ies/spotlight/ies-cookie-reflector2.tga";
							public const string IesCookieReflector3 = "assets/content/props/light_fixtures/v2/ies/spotlight/ies-cookie-reflector3.tga";
							public const string IesCookieReflector4 = "assets/content/props/light_fixtures/v2/ies/spotlight/ies-cookie-reflector4.tga";
							public const string IesCookieReflector5 = "assets/content/props/light_fixtures/v2/ies/spotlight/ies-cookie-reflector5.tga";
						}
					}
				}
			}
			public static class Paintings
			{
				public static class Textures
				{
					public const string LandscapeCity = "assets/content/props/paintings/textures/landscape_city.tga";
					public const string LandscapeMountains = "assets/content/props/paintings/textures/landscape_mountains.tga";
					public const string LandscapeStrangePainting = "assets/content/props/paintings/textures/landscape_strange_painting.tga";
					public const string PortraitFamilly = "assets/content/props/paintings/textures/portrait_familly.tga";
					public const string PortraitManTractor = "assets/content/props/paintings/textures/portrait_man_tractor.tga";
				}
			}
		}

		public static class Shaders
		{
			public static class Resources
			{
				public static class Textures
				{
					public const string BlueNoise32 = "assets/content/shaders/resources/textures/bluenoise_32.png";
					public const string Envbrdflut = "assets/content/shaders/resources/textures/envbrdflut.png";
					public const string Noise2dHf64 = "assets/content/shaders/resources/textures/noise2d_hf_64.png";
					public const string PfgdGgx = "assets/content/shaders/resources/textures/pfgd_ggx.exr";
					public const string SkinH = "assets/content/shaders/resources/textures/skin_h.tga";
					public const string SkinN = "assets/content/shaders/resources/textures/skin_n.tga";
				}
			}
			public static class Tools
			{
				public static class LodbakerTestprefab
				{
					public static class Textures
					{
						public const string LodbakerTestprefabLodDiffuse = "assets/content/shaders/tools/lodbakertestprefab/textures/lodbakertestprefab_lod_diffuse.png";
						public const string LodbakerTestprefabLodNormals = "assets/content/shaders/tools/lodbakertestprefab/textures/lodbakertestprefab_lod_normals.png";
						public const string LodbakerTestprefabLodSpecGloss = "assets/content/shaders/tools/lodbakertestprefab/textures/lodbakertestprefab_lod_specgloss.png";
					}
				}
			}
		}

		public static class Textures
		{
			public static class Debug
			{
				public const string MacbethChart = "assets/content/textures/debug/macbeth_chart.png";
				public const string MetalGradient = "assets/content/textures/debug/metal_gradient.tga";
			}
			public static class Decals
			{
				public const string DecalArrowStraightABc = "assets/content/textures/decals/decal_arrow_straight_a_bc.tga";
				public const string DecalBloodBc = "assets/content/textures/decals/decal_blood_bc.tga";
				public const string DecalBloodSg = "assets/content/textures/decals/decal_blood_sg.tga";
				public const string DecalBloodSplatter01Bc = "assets/content/textures/decals/decal_blood_splatter_01_bc.tga";
				public const string DecalBloodSplatter01Sg = "assets/content/textures/decals/decal_blood_splatter_01_sg.tga";
				public const string DecalBloodSplatter02Bc = "assets/content/textures/decals/decal_blood_splatter_02_bc.tga";
				public const string DecalBloodSplatter03Bc = "assets/content/textures/decals/decal_blood_splatter_03_bc.tga";
				public const string DecalBloodSplatter03Sg = "assets/content/textures/decals/decal_blood_splatter_03_sg.tga";
				public const string DecalBluntImpact01Bc = "assets/content/textures/decals/decal_blunt_impact_01_bc.tga";
				public const string DecalBulletDirtBc01 = "assets/content/textures/decals/decal_bullet_dirt_bc_01.tga";
				public const string DecalBulletDirtNrm01 = "assets/content/textures/decals/decal_bullet_dirt_nrm_01.tga";
				public const string DecalBulletDirtSg01 = "assets/content/textures/decals/decal_bullet_dirt_sg_01.tga";
				public const string DecalBulletFleshEntry01Bc = "assets/content/textures/decals/decal_bullet_flesh_entry_01_bc.tga";
				public const string DecalBulletFleshEntry01Sg = "assets/content/textures/decals/decal_bullet_flesh_entry_01_sg.tga";
				public const string DecalBulletFleshExit01Bc = "assets/content/textures/decals/decal_bullet_flesh_exit_01_bc.tga";
				public const string DecalBulletFleshExit01Sg = "assets/content/textures/decals/decal_bullet_flesh_exit_01_sg.tga";
				public const string DecalBulletForestBc01 = "assets/content/textures/decals/decal_bullet_forest_bc_01.tga";
				public const string DecalBulletForestNrm01 = "assets/content/textures/decals/decal_bullet_forest_nrm_01.tga";
				public const string DecalBulletGlass2Bc = "assets/content/textures/decals/decal_bullet_glass2_bc.tga";
				public const string DecalBulletGlass3Bc = "assets/content/textures/decals/decal_bullet_glass3_bc.tga";
				public const string DecalBulletGlassBc = "assets/content/textures/decals/decal_bullet_glass_bc.tga";
				public const string DecalBulletHole01Bc = "assets/content/textures/decals/decal_bullethole01_bc.tga";
				public const string DecalBulletHole01Sg = "assets/content/textures/decals/decal_bullethole01_sg.tga";
				public const string DecalBulletHole02Bc = "assets/content/textures/decals/decal_bullethole02_bc.tga";
				public const string DecalBulletHole02Sg = "assets/content/textures/decals/decal_bullethole02_sg.tga";
				public const string DecalBulletHole03Bc = "assets/content/textures/decals/decal_bullethole03_bc.tga";
				public const string DecalBulletHole03Sg = "assets/content/textures/decals/decal_bullethole03_sg.tga";
				public const string DecalBulletHole04Bc = "assets/content/textures/decals/decal_bullethole04_bc.tga";
				public const string DecalBulletHole04Sg = "assets/content/textures/decals/decal_bullethole04_sg.tga";
				public const string DecalBulletHole05Bc = "assets/content/textures/decals/decal_bullethole05_bc.tga";
				public const string DecalBulletHoleMetal01Bc = "assets/content/textures/decals/decal_bulletholemetal01_bc.tga";
				public const string DecalBulletHoleWood01Bc = "assets/content/textures/decals/decal_bulletholewood01_bc.tga";
				public const string DecalBulletHoleWood01Sg = "assets/content/textures/decals/decal_bulletholewood01_sg.tga";
				public const string DecalBulletHoleWood02Bc = "assets/content/textures/decals/decal_bulletholewood02_bc.tga";
				public const string DecalBulletHoleWood02Sg = "assets/content/textures/decals/decal_bulletholewood02_sg.tga";
				public const string DecalBulletHoleWood03Bc = "assets/content/textures/decals/decal_bulletholewood03_bc.tga";
				public const string DecalBulletHoleWood03Sg = "assets/content/textures/decals/decal_bulletholewood03_sg.tga";
				public const string DecalBulletHoleWood04Bc = "assets/content/textures/decals/decal_bulletholewood04_bc.tga";
				public const string DecalBulletHoleWood04Sg = "assets/content/textures/decals/decal_bulletholewood04_sg.tga";
				public const string DecalBulletImpactTundra01 = "assets/content/textures/decals/decal_bullet_impact_tundra_01.tga";
				public const string DecalBulletMetal01Bc = "assets/content/textures/decals/decal_bullet_metal_01_bc.tga";
				public const string DecalBulletMetal01Sg = "assets/content/textures/decals/decal_bullet_metal_01_sg.tga";
				public const string DecalBulletMetal02Bc = "assets/content/textures/decals/decal_bullet_metal_02_bc.tga";
				public const string DecalBulletMetal02Sg = "assets/content/textures/decals/decal_bullet_metal_02_sg.tga";
				public const string DecalBulletMetal03Bc = "assets/content/textures/decals/decal_bullet_metal_03_bc.tga";
				public const string DecalBulletMetal03Sg = "assets/content/textures/decals/decal_bullet_metal_03_sg.tga";
				public const string DecalBulletRoadBc01 = "assets/content/textures/decals/decal_bullet_road_bc_01.tga";
				public const string DecalBulletRoadNrm01 = "assets/content/textures/decals/decal_bullet_road_nrm_01.tga";
				public const string DecalBulletSand01Bc = "assets/content/textures/decals/decal_bullet_sand_01_bc.tga";
				public const string DecalBulletSand01Sg = "assets/content/textures/decals/decal_bullet_sand_01_sg.tga";
				public const string DecalBulletSandBagBc = "assets/content/textures/decals/decal_bullet_sandbag_bc.tga";
				public const string DecalBulletSnow01Bc = "assets/content/textures/decals/decal_bullet_snow_01_bc.tga";
				public const string DecalBulletSnow01Sg = "assets/content/textures/decals/decal_bullet_snow_01_sg.tga";
				public const string DecalBulletStone01Bc = "assets/content/textures/decals/decal_bullet_stone_01_bc.tga";
				public const string DecalBulletStone01Sg = "assets/content/textures/decals/decal_bullet_stone_01_sg.tga";
				public const string DecalChillZoneBc = "assets/content/textures/decals/decal_chillzone_bc.png";
				public const string DecalCompoundSignsBc = "assets/content/textures/decals/decal_compound_signs_bc.tga";
				public const string DecalConcreteCracksABc = "assets/content/textures/decals/decal_concrete_cracks_a_bc.tga";
				public const string DecalConcreteLeaksABc = "assets/content/textures/decals/decal_concrete_leaks_a_bc.tga";
				public const string DecalConcreteLeaksBBc = "assets/content/textures/decals/decal_concrete_leaks_b_bc.tga";
				public const string DecalConcreteLeaksCBc = "assets/content/textures/decals/decal_concrete_leaks_c_bc.tga";
				public const string DecalConcreteLeaksDBc = "assets/content/textures/decals/decal_concrete_leaks_d_bc.tga";
				public const string DecalConcreteLeaksEBc = "assets/content/textures/decals/decal_concrete_leaks_e_bc.tga";
				public const string DecalConcreteLeaksFBc = "assets/content/textures/decals/decal_concrete_leaks_f_bc.tga";
				public const string DecalExplosion01Bc = "assets/content/textures/decals/decal_explosion01_bc.tga";
				public const string DecalExplosionBc = "assets/content/textures/decals/decal_explosion_bc.tga";
				public const string DecalFootprintHumanBareSandLeftBc = "assets/content/textures/decals/decal_footprint_human_bare_sand_left_bc.tga";
				public const string DecalFootprintHumanBareSandRightBc = "assets/content/textures/decals/decal_footprint_human_bare_sand_right_bc.tga";
				public const string DecalFootprintHumanBareSandSg = "assets/content/textures/decals/decal_footprint_human_bare_sand_sg.tga";
				public const string DecalFootprintHumanBareSnowLeftBc = "assets/content/textures/decals/decal_footprint_human_bare_snow_left_bc.tga";
				public const string DecalFootprintHumanBareSnowRightBc = "assets/content/textures/decals/decal_footprint_human_bare_snow_right_bc.tga";
				public const string DecalFootprintHumanBootSandLeftBc = "assets/content/textures/decals/decal_footprint_human_boot_sand_left_bc.tga";
				public const string DecalFootprintHumanBootSandRightBc = "assets/content/textures/decals/decal_footprint_human_boot_sand_right_bc.tga";
				public const string DecalFootprintHumanBootSnowLeftBc = "assets/content/textures/decals/decal_footprint_human_boot_snow_left_bc.tga";
				public const string DecalFootprintHumanBootSnowRightBc = "assets/content/textures/decals/decal_footprint_human_boot_snow_right_bc.tga";
				public const string DecalKargo1X4Bc = "assets/content/textures/decals/decal_kargo_1x4_bc.tga";
				public const string DecalKeepOutBc = "assets/content/textures/decals/decal_keep_out_bc.tga";
				public const string DecalLabelOilABc = "assets/content/textures/decals/decal_label_oil_a_bc.tga";
				public const string DecalRifleBulletImpactMetalABc = "assets/content/textures/decals/decal_rifle_bullet_impact_metal_a_bc.tga";
				public const string DecalRifleBulletImpactMetalASg = "assets/content/textures/decals/decal_rifle_bullet_impact_metal_a_sg.tga";
				public const string DecalRoadDebrisBc = "assets/content/textures/decals/decal_road_debris_bc.tga";
				public const string DecalRoadDebrisSg = "assets/content/textures/decals/decal_road_debris_sg.tga";
				public const string DecalRustMillsShippingBc = "assets/content/textures/decals/decal_rust_mills_shipping_bc.tga";
				public const string DecalSeaweedPlaneSeaweedDecalBc = "assets/content/textures/decals/decal_seaweedplane_seaweeddecal_bc.tga";
				public const string DecalSeaweedPlaneSeaweedDecalMg = "assets/content/textures/decals/decal_seaweedplane_seaweeddecal_mg.tga";
				public const string DecalSeaweedPlaneSeaweedDecalSss = "assets/content/textures/decals/decal_seaweedplane_seaweeddecal_sss.tga";
				public const string DecalShippingContainerDecalRepackBcBc = "assets/content/textures/decals/decal_shipping_container_decal_repack_bc_bc.tga";
				public const string DecalShippingContainerDecalRepackSg = "assets/content/textures/decals/decal_shipping_container_decal_repack_sg.tga";
				public const string DecalStabFlesh01Bc = "assets/content/textures/decals/decal_stab_flesh_01_bc.tga";
				public const string DecalStabFlesh01Sg = "assets/content/textures/decals/decal_stab_flesh_01_sg.tga";
				public const string DecalStranglerFigWallDecalDiff = "assets/content/textures/decals/decal_strangler_fig_wall_decal_diff.tga";
				public const string DecalStranglerFigWallDecalSg = "assets/content/textures/decals/decal_strangler_fig_wall_decal_sg.tga";
				public const string DecalTreebase1Bc = "assets/content/textures/decals/decal_treebase1_bc.tga";
				public const string DecalTreebase1Sg = "assets/content/textures/decals/decal_treebase1_sg.tga";
				public const string DecalTreebase2Bc = "assets/content/textures/decals/decal_treebase2_bc.tga";
				public const string DecalTreebase2Sg = "assets/content/textures/decals/decal_treebase2_sg.tga";
				public const string DecalVertiigoGraffitiBc = "assets/content/textures/decals/decal_vertiigo_graffiti_bc.png";
				public const string DecalWarningBiohazardABc = "assets/content/textures/decals/decal_warning_biohazard_a_bc.tga";
				public const string DecalWarningExplosiveABc = "assets/content/textures/decals/decal_warning_explosive_a_bc.tga";
				public const string DecalWarningFuelABc = "assets/content/textures/decals/decal_warning_fuel_a_bc.tga";
				public const string DecalWarningNonHazardousBc = "assets/content/textures/decals/decal_warning_non_hazardous_bc.png";
				public const string DecalWarningPoisonBc = "assets/content/textures/decals/decal_warning_poison_bc.png";
				public const string DecalWarningRadioactiveABc = "assets/content/textures/decals/decal_warning_radioactive_a_bc.tga";
				public const string DecalWarningRecycleBc = "assets/content/textures/decals/decal_warning_recycle_bc.png";
				public const string DecalWarningVolatileBc = "assets/content/textures/decals/decal_warning_volatile_bc.png";
				public const string DecalXSprayABc = "assets/content/textures/decals/decal_xspray_a_bc.png";
				public const string DecalXSprayARed = "assets/content/textures/decals/decal_xspray_a_red.tga";
			}
			public static class Detail
			{
				public const string AsphaltADetail = "assets/content/textures/detail/asphalt_a_detail.tga";
				public const string ConcreteADetail = "assets/content/textures/detail/concrete_a_detail.tga";
				public const string ConcreteBDetail = "assets/content/textures/detail/concrete_b_detail.tga";
				public const string FabricADetail = "assets/content/textures/detail/fabric_a_detail.tga";
				public const string GenericMask1 = "assets/content/textures/detail/generic_mask1.tga";
				public const string MetalADetail = "assets/content/textures/detail/metal_a_detail.tga";
				public const string MetalCDetail = "assets/content/textures/detail/metal_c_detail.tga";
				public const string MetalDDetail = "assets/content/textures/detail/metal_d_detail.tga";
				public const string PlasterADetail = "assets/content/textures/detail/plaster_a_detail.tga";
				public const string PlasterBDetail = "assets/content/textures/detail/plaster_b_detail.tga";
				public const string RandomColorADetail = "assets/content/textures/detail/random_color_a_detail.tga";
				public const string RandomColorADetailMask = "assets/content/textures/detail/random_color_a_detail_mask.tga";
				public const string RustADetail = "assets/content/textures/detail/rust_a_detail.tga";
				public const string RustBDetail = "assets/content/textures/detail/rust_b_detail.tga";
				public const string RustCDetail = "assets/content/textures/detail/rust_c_detail.tga";
			}
		}

		public static class Ui
		{
			public const string MugshotUnknown = "assets/content/ui/mugshot_unknown.png";
			public const string NmsDirt = "assets/content/ui/nms-dirt.png";
			public const string OverlayBleeding = "assets/content/ui/overlay_bleeding.png";
			public const string UiGradientDownTight = "assets/content/ui/ui.gradient.down.tight.psd";
			public const string UiSpashScreen = "assets/content/ui/ui.spashscreen.psd";

			public static class GameUi
			{
				public const string UiCrosshairCircle = "assets/content/ui/gameui/ui.crosshair.circle.png";

				public static class AttackHeli
				{
					public static class Compass
					{
						public const string CompassStrip = "assets/content/ui/gameui/attackheli/compass/compass_strip.psd";
						public const string CompassStrip2 = "assets/content/ui/gameui/attackheli/compass/compass_strip_2.psd";
						public const string CompassStripDigital = "assets/content/ui/gameui/attackheli/compass/compass_strip_digital.psd";
					}
				}

				public static class CardGames
				{
					public static class Deck
					{
						public static class Jokers
						{
							public const string JokerBlack = "assets/content/ui/gameui/cardgames/deck/jokers/joker_black.png";
							public const string JokerMixed = "assets/content/ui/gameui/cardgames/deck/jokers/joker_mixed.png";
							public const string JokerRed = "assets/content/ui/gameui/cardgames/deck/jokers/joker_red.png";
						}
					}
				}
			}
		}

		public static class Vehicles
		{
			public static class ModularCar
			{
				public static class Models
				{
					public static class Materials
					{
						public static class Textures
						{
							public const string CheckEngineLight = "assets/content/vehicles/modularcar/models/materials/textures/checkenginelight.tga";
							public const string LowGasLight = "assets/content/vehicles/modularcar/models/materials/textures/lowgaslight.tga";
						}
					}
				}
			}
		}
	}
	public static class Icons
	{
		public const string CircleGradientWhite = "assets/icons/circle_gradient_white.png";
		public const string CursorHand = "assets/icons/cursor-hand.png";
		public const string GestureRaiseTheRoofAlternative = "assets/icons/gestures/gesture-raise-the-roof-alternative.png";
		public const string Grenade = "assets/icons/grenade.png";
		public const string SteamInventory = "assets/icons/steam_inventory.png";
	}
	public static class Prefabs
	{
		public const string HolosightReticleStandard = "assets/prefabs/weapon mods/holosight/holosight.reticle.standard.png";
		public const string MissionIconComplete = "assets/prefabs/missions/textures/mission_icon_complete.png";
		public const string ReclaimStencil = "assets/prefabs/gamemodes/objects/reclaim/materials/reclaim_stencil.png";

		public static class Tools
		{
			public static class SprayCan
			{
				public static class Sprays
				{
					public const string BeanCan = "assets/prefabs/tools/spraycan/sprays/bean_can.png";
					public const string CandleHat = "assets/prefabs/tools/spraycan/sprays/candle_hat.png";
					public const string FacepunchLogo = "assets/prefabs/tools/spraycan/sprays/facepunch_logo.png";
					public const string FrogBoot = "assets/prefabs/tools/spraycan/sprays/frog_boot.png";
					public const string Hazmat = "assets/prefabs/tools/spraycan/sprays/hazmat.png";
					public const string Rock = "assets/prefabs/tools/spraycan/sprays/rock.png";
					public const string RustLogo = "assets/prefabs/tools/spraycan/sprays/rust_logo.png";
					public const string Target = "assets/prefabs/tools/spraycan/sprays/target.png";
					public const string WhensWhip = "assets/prefabs/tools/spraycan/sprays/whens_whip.png";

					public static class Skins
					{
						public static class ArtistPackDlc
						{
							public static class Static
							{
								public static class Materials
								{
									public const string ArtistRosette1st = "assets/prefabs/tools/spraycan/sprays/skins/artist.pack.dlc/static/materials/artist_rosette_1st.png";
									public const string ArtistRosette2nd = "assets/prefabs/tools/spraycan/sprays/skins/artist.pack.dlc/static/materials/artist_rosette_2nd.png";
									public const string ArtistRosette3rd = "assets/prefabs/tools/spraycan/sprays/skins/artist.pack.dlc/static/materials/artist_rosette_3rd.png";
									public const string ArtistRosetteLast = "assets/prefabs/tools/spraycan/sprays/skins/artist.pack.dlc/static/materials/artist_rosette_last.png";
								}
							}
						}
						public static class IndustrialDlc
						{
							public static class Static
							{
								public static class Materials
								{
									public const string IndustrialKeepout = "assets/prefabs/tools/spraycan/sprays/skins/industrial.dlc/static/materials/industrial_keepout.png";
									public const string IndustrialToxic = "assets/prefabs/tools/spraycan/sprays/skins/industrial.dlc/static/materials/industrial_toxic.png";
								}
							}
						}
						public static class JungleDlc
						{
							public static class Static
							{
								public static class Materials
								{
									public const string JungleSkull = "assets/prefabs/tools/spraycan/sprays/skins/jungledlc/static/materials/jungle_skull.png";
									public const string JungleTiger = "assets/prefabs/tools/spraycan/sprays/skins/jungledlc/static/materials/jungle_tiger.png";
								}
							}
						}
					}
				}
			}
		}

		public static class WallPaper
		{
			public static class Models
			{
				public static class Textures
				{
					public static class WallPaperTools
					{
						public const string CeilingPaperBc = "assets/prefabs/wallpaper/models/textures/wallpaper_tools/ceilingpaper_bc.tga";
						public const string CeilingPaperMask = "assets/prefabs/wallpaper/models/textures/wallpaper_tools/ceilingpaper_mask.tga";
						public const string CeilingPaperSg = "assets/prefabs/wallpaper/models/textures/wallpaper_tools/ceilingpaper_sg.tga";
						public const string FloorPaperToolBc = "assets/prefabs/wallpaper/models/textures/wallpaper_tools/floorpaper_tool_bc.tga";
						public const string FloorPaperToolMask = "assets/prefabs/wallpaper/models/textures/wallpaper_tools/floorpaper_tool_mask.tga";
						public const string FloorPaperToolSg = "assets/prefabs/wallpaper/models/textures/wallpaper_tools/floorpaper_tool_sg.tga";
						public const string WallPaperRollBc = "assets/prefabs/wallpaper/models/textures/wallpaper_tools/wallpaper_roll_bc.tga";
						public const string WallPaperRollMask = "assets/prefabs/wallpaper/models/textures/wallpaper_tools/wallpaper_roll_mask.tga";
						public const string WallPaperRollSg = "assets/prefabs/wallpaper/models/textures/wallpaper_tools/wallpaper_roll_sg.tga";
					}
				}
			}
		}
	}
	public static class StandardAssets
	{
		public static class Effects
		{
			public static class ImageEffects
			{
				public static class Textures
				{
					public const string ColorCorrectionRamp = "assets/standard assets/effects/imageeffects/textures/color correction ramp.png";
					public const string Contrastenhanced3d16 = "assets/standard assets/effects/imageeffects/textures/contrastenhanced3d16.png";
					public const string GrayscaleRamp = "assets/standard assets/effects/imageeffects/textures/grayscale ramp.png";
					public const string Hexshape = "assets/standard assets/effects/imageeffects/textures/hexshape.psd";
					public const string MotionBlurjitter = "assets/standard assets/effects/imageeffects/textures/motionblurjitter.png";
					public const string Neutral3d16 = "assets/standard assets/effects/imageeffects/textures/neutral3d16.png";
					public const string Noise = "assets/standard assets/effects/imageeffects/textures/noise.png";
					public const string Noiseandgrain = "assets/standard assets/effects/imageeffects/textures/noiseandgrain.png";
					public const string Noiseeffectgrain = "assets/standard assets/effects/imageeffects/textures/noiseeffectgrain.png";
					public const string NoiseEffectscratch = "assets/standard assets/effects/imageeffects/textures/noiseeffectscratch.png";
					public const string Randomvectors = "assets/standard assets/effects/imageeffects/textures/randomvectors.png";
					public const string Sphereshape = "assets/standard assets/effects/imageeffects/textures/sphereshape.psd";
					public const string VignetteMask = "assets/standard assets/effects/imageeffects/textures/vignettemask.png";
				}
			}
		}
		public static class Particles
		{
			public static class Sources
			{
				public static class Textures
				{
					public const string Smoke = "assets/standard assets/particles/sources/textures/smoke.tif";
					public const string Smoke3 = "assets/standard assets/particles/sources/textures/smoke3.tif";
					public const string Smoke4 = "assets/standard assets/particles/sources/textures/smoke4.tif";
					public const string Spark = "assets/standard assets/particles/sources/textures/spark.tif";
				}
			}
		}
		public static class ThirdParty
		{
			public static class CamelotvfxFireSmoke
			{
				public static class SpriteSheetS
				{
					public const string FireSpritesV1 = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/fire_sprites_v1.png";
					public const string FireSpritesV1ReMapped = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/fire_sprites_v1_remapped.png";
					public const string FireSpritesV2 = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/fire_sprites_v2.png";
					public const string FireSpritesV3 = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/fire_sprites_v3.png";
					public const string FlamethrowerSpritesV1 = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/flamethrower_sprites_v1.png";
					public const string FlamethrowerSpritesV2 = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/flamethrower_sprites_v2.png";
					public const string FlamethrowerSpritesV3 = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/flamethrower_sprites_v3.png";
					public const string OilRigSpritesV1 = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/oil_rig_sprites_v1.png";
					public const string OilRigSpritesV1Emission = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/oil_rig_sprites_v1_emission.png";
					public const string OilRigSpritesV2 = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/oil_rig_sprites_v2.png";
					public const string OilRigSpritesV2Emission = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/oil_rig_sprites_v2_emission.png";
					public const string OilRigSpritesV2Emission2 = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/oil_rig_sprites_v2_emission_2.png";
					public const string OilRigSpritesV3 = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/oil_rig_sprites_v3.png";
					public const string OilRigSpritesV3Emission = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/oil_rig_sprites_v3_emission.png";
					public const string SmokeSpritesDense = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/smoke_sprites_dense.png";
					public const string SmokeSpritesDense02 = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/smoke_sprites_dense_02.png";
					public const string SmokeSpritesDense02EmissionV1 = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/smoke_sprites_dense_02_emission_v1.png";
					public const string SmokeSpritesDense03 = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/smoke_sprites_dense_03.png";
					public const string SmokeSpritesLight = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/smoke_sprites_light.png";
					public const string SmokeSpritesMed = "assets/standard assets/third party/camelotvfx_ fire&smoke/sprite_sheets/smoke_sprites_med.png";
				}
			}
			public static class CamelotvfxAdvWaterFx
			{
				public static class SpriteSheetS
				{
					public const string BubblesV1 = "assets/standard assets/third party/camelotvfx_adv_water_fx/sprite_sheets/bubbles_v1.png";
					public const string BubblesV2 = "assets/standard assets/third party/camelotvfx_adv_water_fx/sprite_sheets/bubbles_v2.png";
					public const string BubblesV3 = "assets/standard assets/third party/camelotvfx_adv_water_fx/sprite_sheets/bubbles_v3.png";
					public const string FoamV1 = "assets/standard assets/third party/camelotvfx_adv_water_fx/sprite_sheets/foam_v1.png";
					public const string FoamV2 = "assets/standard assets/third party/camelotvfx_adv_water_fx/sprite_sheets/foam_v2.png";
					public const string FoamV3 = "assets/standard assets/third party/camelotvfx_adv_water_fx/sprite_sheets/foam_v3.png";
					public const string MistV1 = "assets/standard assets/third party/camelotvfx_adv_water_fx/sprite_sheets/mist_v1.png";
					public const string MistV2 = "assets/standard assets/third party/camelotvfx_adv_water_fx/sprite_sheets/mist_v2.png";
					public const string MistV3 = "assets/standard assets/third party/camelotvfx_adv_water_fx/sprite_sheets/mist_v3.png";
					public const string WaterSplashV1 = "assets/standard assets/third party/camelotvfx_adv_water_fx/sprite_sheets/water_splash_v1.png";
					public const string WaterSplashV2 = "assets/standard assets/third party/camelotvfx_adv_water_fx/sprite_sheets/water_splash_v2.png";
					public const string WaterSplashV3 = "assets/standard assets/third party/camelotvfx_adv_water_fx/sprite_sheets/water_splash_v3.png";
				}
			}
			public static class Colorful
			{
				public static class Resources
				{
					public const string Grayscaleramp = "assets/standard assets/third party/colorful/resources/grayscaleramp.png";
					public const string Heatramp = "assets/standard assets/third party/colorful/resources/heatramp.png";
					public const string Lookupsource = "assets/standard assets/third party/colorful/resources/lookupsource.png";
				}
			}
			public static class DetailedPyroFx
			{
				public static class Textures
				{
					public static class _1024
					{
						public const string Explosion011024 = "assets/standard assets/third party/detailed_pyro_fx/textures/1024/explosion01_1024.png";
						public const string Explosion021024 = "assets/standard assets/third party/detailed_pyro_fx/textures/1024/explosion02_1024.png";
						public const string Explosion031024 = "assets/standard assets/third party/detailed_pyro_fx/textures/1024/explosion03_1024.png";
						public const string Fire011024 = "assets/standard assets/third party/detailed_pyro_fx/textures/1024/fire01_1024.png";
						public const string Fire021024 = "assets/standard assets/third party/detailed_pyro_fx/textures/1024/fire02_1024.png";
						public const string Flare01256 = "assets/standard assets/third party/detailed_pyro_fx/textures/1024/flare_01_256.png";
						public const string Flare02256 = "assets/standard assets/third party/detailed_pyro_fx/textures/1024/flare_02_256.png";
						public const string Smoke011024 = "assets/standard assets/third party/detailed_pyro_fx/textures/1024/smoke01_1024.png";
						public const string Smoke021024 = "assets/standard assets/third party/detailed_pyro_fx/textures/1024/smoke02_1024.png";
						public const string Smoke031024 = "assets/standard assets/third party/detailed_pyro_fx/textures/1024/smoke03_1024.png";
					}
					public static class _4096
					{
						public const string Explosion014097 = "assets/standard assets/third party/detailed_pyro_fx/textures/4096/explosion01_4097.png";
						public const string Explosion024097 = "assets/standard assets/third party/detailed_pyro_fx/textures/4096/explosion02_4097.png";
						public const string Explosion034097 = "assets/standard assets/third party/detailed_pyro_fx/textures/4096/explosion03_4097.png";
						public const string Fire014096 = "assets/standard assets/third party/detailed_pyro_fx/textures/4096/fire01_4096.png";
						public const string Fire024096 = "assets/standard assets/third party/detailed_pyro_fx/textures/4096/fire02_4096.png";
						public const string Flare01 = "assets/standard assets/third party/detailed_pyro_fx/textures/4096/flare_01.png";
						public const string Flare02 = "assets/standard assets/third party/detailed_pyro_fx/textures/4096/flare_02.png";
						public const string Smoke014096 = "assets/standard assets/third party/detailed_pyro_fx/textures/4096/smoke01_4096.png";
						public const string Smoke024096 = "assets/standard assets/third party/detailed_pyro_fx/textures/4096/smoke02_4096.png";
						public const string Smoke034096 = "assets/standard assets/third party/detailed_pyro_fx/textures/4096/smoke03_4096.png";
					}
				}
			}
			public static class Lensdirtiness
			{
				public const string Lensdirtiness01 = "assets/standard assets/third party/lensdirtiness/lensdirtiness_01.jpg";
				public const string TestImage = "assets/standard assets/third party/lensdirtiness/testimage.jpg";
			}
			public static class StormEffects
			{
				public static class _2Particles
				{
					public static class Textures
					{
						public const string Cloud = "assets/standard assets/third party/storm effects/2 - particles/textures/cloud.png";
						public const string Cloud2 = "assets/standard assets/third party/storm effects/2 - particles/textures/cloud2.png";
						public const string Cloud3 = "assets/standard assets/third party/storm effects/2 - particles/textures/cloud3.png";
						public const string Debris = "assets/standard assets/third party/storm effects/2 - particles/textures/debris.png";
						public const string Debriscloud = "assets/standard assets/third party/storm effects/2 - particles/textures/debriscloud.tga";
						public const string Rain = "assets/standard assets/third party/storm effects/2 - particles/textures/rain.png";
						public const string Raindrop = "assets/standard assets/third party/storm effects/2 - particles/textures/raindrop.png";
						public const string Rainmed = "assets/standard assets/third party/storm effects/2 - particles/textures/rainmed.png";
						public const string Rainmist = "assets/standard assets/third party/storm effects/2 - particles/textures/rainmist.png";
						public const string Rainsmall = "assets/standard assets/third party/storm effects/2 - particles/textures/rainsmall.png";
						public const string Rainwind = "assets/standard assets/third party/storm effects/2 - particles/textures/rainwind.png";
						public const string Snowflake32 = "assets/standard assets/third party/storm effects/2 - particles/textures/snowflake32.png";
						public const string Snowmed = "assets/standard assets/third party/storm effects/2 - particles/textures/snowmed.png";
						public const string Snowsmall = "assets/standard assets/third party/storm effects/2 - particles/textures/snowsmall.png";
						public const string Tornado = "assets/standard assets/third party/storm effects/2 - particles/textures/tornado.png";
						public const string Wind = "assets/standard assets/third party/storm effects/2 - particles/textures/wind.png";
					}
				}
			}
			public static class TimeOfDay
			{
				public static class Assets
				{
					public static class Textures
					{
						public const string BayerMatrix = "assets/standard assets/third party/time of day/assets/textures/bayer_matrix.tga";
						public const string CloudAtlas = "assets/standard assets/third party/time of day/assets/textures/cloud_atlas.tga";
						public const string CloudLayers = "assets/standard assets/third party/time of day/assets/textures/cloud_layers.tga";
						public const string CloudNormals = "assets/standard assets/third party/time of day/assets/textures/cloud_normals.tga";
						public const string MoonTexture = "assets/standard assets/third party/time of day/assets/textures/moon_texture.tga";
					}
				}
			}
		}
	}
	public static class ThirdParty
	{
		public const string EffectIcon = "assets/third party/amplifyocclusion/plugins/editor/resources/effect-icon.tiff";
		public const string Noise = "assets/third party/cathodeanaloguevideo/resources/noise.png";
		public const string Texeldensitygrad = "assets/third party/visualizetexeldensity/resources/texeldensitygrad.png";

		public static class CinematicEffects
		{
			public static class ToneMappingcolorgrading
			{
				public static class Helpers
				{
					public const string Neutrallut16 = "assets/third party/cinematiceffects/tonemappingcolorgrading/helpers/neutrallut16.png";
					public const string Neutrallut32 = "assets/third party/cinematiceffects/tonemappingcolorgrading/helpers/neutrallut32.png";
				}
			}
		}

		public static class FimpossibleCreations
		{
			public static class Editor
			{
				public static class PluginsEditorAnimating
				{
					public static class LegsAnimator
					{
						public static class Resources
						{
							public const string Armsway = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/armsway.png";
							public const string Rootsway = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/rootsway.png";
							public const string Spinesway = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/spinesway.png";

							public static class LegsAnimator
							{
								public const string Automotion = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/automotion.png";
								public const string Dynamichips = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/dynamichips.png";
								public const string Footglue = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/footglue.png";
								public const string Footstep = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/footstep.png";
								public const string Legcast = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/legcast.png";
								public const string Legmove = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/legmove.png";
								public const string SprEndleg = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_endleg.png";
								public const string SprFootrotate = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_footrotate.png";
								public const string SprIk = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_ik.png";
								public const string SprLegalign1 = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_legalign1.png";
								public const string SprLeggl = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_leggl.png";
								public const string SprLegik = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_legik.png";
								public const string SprLegmot = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_legmot.png";
								public const string SprLegmot2 = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_legmot2.png";
								public const string SprLegmotion1Fw = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_legmotion1.fw.png";
								public const string SprLegsanimIcon = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_legsanimicon.png";
								public const string SprLegscrop = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_legscrop.png";
								public const string SprLleg = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_lleg.png";
								public const string SprLlegoff = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_llegoff.png";
								public const string SprMidleg = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_midleg.png";
								public const string SprOppoSite = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_opposite.png";
								public const string SprRleg = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_rleg.png";
								public const string SprRlegoff = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_rlegoff.png";
								public const string SprSmendleg = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_smendleg.png";
								public const string SprSmmidleg = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_smmidleg.png";
								public const string SprSmStartleg = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_smstartleg.png";
								public const string SprUpperleg = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/spr_upperleg.png";
								public const string Stabilize = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/stabilize.png";
								public const string StepDown = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/stepdown.png";
								public const string Stepping = "assets/third party/fimpossible creations/editor/plugins - editor - animating/legs animator/resources/legs animator/stepping.png";
							}
						}
					}
					public static class LookAnimator
					{
						public static class Resources
						{
							public static class LookAnimator
							{
								public const string Backbones = "assets/third party/fimpossible creations/editor/plugins - editor - animating/look animator/resources/look animator/backbones.png";
								public const string Birdmode = "assets/third party/fimpossible creations/editor/plugins - editor - animating/look animator/resources/look animator/birdmode.png";
								public const string Compensation = "assets/third party/fimpossible creations/editor/plugins - editor - animating/look animator/resources/look animator/compensation.png";
								public const string LookanimatorIcon = "assets/third party/fimpossible creations/editor/plugins - editor - animating/look animator/resources/look animator/lookanimator_icon.png";
								public const string LookanimatorSmallIcon = "assets/third party/fimpossible creations/editor/plugins - editor - animating/look animator/resources/look animator/lookanimator_smallicon.png";
								public const string Lookeyes = "assets/third party/fimpossible creations/editor/plugins - editor - animating/look animator/resources/look animator/lookeyes.png";
							}
						}
					}
					public static class SpineAnimator
					{
						public static class Resources
						{
							public static class SpineAnimator
							{
								public const string Leadingl = "assets/third party/fimpossible creations/editor/plugins - editor - animating/spine animator/resources/spine animator/leadingl.png";
								public const string Leadingr = "assets/third party/fimpossible creations/editor/plugins - editor - animating/spine animator/resources/spine animator/leadingr.png";
								public const string SpineanimatorIcon = "assets/third party/fimpossible creations/editor/plugins - editor - animating/spine animator/resources/spine animator/spineanimator_icon.png";
								public const string SpineanimatorqueuerIcon = "assets/third party/fimpossible creations/editor/plugins - editor - animating/spine animator/resources/spine animator/spineanimatorqueuer icon.png";
								public const string SpineanimatorSmallIcon = "assets/third party/fimpossible creations/editor/plugins - editor - animating/spine animator/resources/spine animator/spineanimator_smallicon.png";
								public const string SpineBoneConnectorIcon = "assets/third party/fimpossible creations/editor/plugins - editor - animating/spine animator/resources/spine animator/spine bone connector icon.png";
								public const string Spinewide = "assets/third party/fimpossible creations/editor/plugins - editor - animating/spine animator/resources/spine animator/spinewide.png";
							}
						}
					}
					public static class TailAnimator
					{
						public static class Resources
						{
							public static class TailAnimator
							{
								public const string Deflection = "assets/third party/fimpossible creations/editor/plugins - editor - animating/tail animator/resources/tail animator/deflection.png";
								public const string FtailCollisionhelperIcon = "assets/third party/fimpossible creations/editor/plugins - editor - animating/tail animator/resources/tail animator/ftail_collisionhelper icon.png";
								public const string IkIcon = "assets/third party/fimpossible creations/editor/plugins - editor - animating/tail animator/resources/tail animator/ikicon.png";
								public const string PartialBlendIcon = "assets/third party/fimpossible creations/editor/plugins - editor - animating/tail animator/resources/tail animator/partialblendicon.png";
								public const string SprTailanimatorwindIcon = "assets/third party/fimpossible creations/editor/plugins - editor - animating/tail animator/resources/tail animator/spr_tailanimatorwindicon.png";
								public const string TailAnimatorCollisionHelperIcon = "assets/third party/fimpossible creations/editor/plugins - editor - animating/tail animator/resources/tail animator/tail animator collision helper icon.png";
								public const string TailAnimatorIcon = "assets/third party/fimpossible creations/editor/plugins - editor - animating/tail animator/resources/tail animator/tail animator icon.png";
								public const string TailAnimatorIconSmall = "assets/third party/fimpossible creations/editor/plugins - editor - animating/tail animator/resources/tail animator/tail animator icon small.png";
								public const string TailAnimatorSkinnerApiIcon = "assets/third party/fimpossible creations/editor/plugins - editor - animating/tail animator/resources/tail animator/tail animator skinner api icon.png";
								public const string TailAnimatorSkinnerIcon = "assets/third party/fimpossible creations/editor/plugins - editor - animating/tail animator/resources/tail animator/tail animator skinner icon.png";
								public const string TailanimatorwindIconsmall = "assets/third party/fimpossible creations/editor/plugins - editor - animating/tail animator/resources/tail animator/tailanimatorwindiconsmall.png";
								public const string WavingIcon = "assets/third party/fimpossible creations/editor/plugins - editor - animating/tail animator/resources/tail animator/wavingicon.png";
								public const string Wind = "assets/third party/fimpossible creations/editor/plugins - editor - animating/tail animator/resources/tail animator/wind.png";
							}
						}
					}
				}
			}
			public static class PluginsAnimating
			{
				public static class GroundFitter
				{
					public static class Scripts
					{
						public static class Editor
						{
							public static class Resources
							{
								public const string FgroundfitterIcon = "assets/third party/fimpossible creations/plugins - animating/ground fitter/scripts/editor/resources/fgroundfitter icon.png";
								public const string FgroundfitterMovementIcon = "assets/third party/fimpossible creations/plugins - animating/ground fitter/scripts/editor/resources/fgroundfitter_movement icon.png";
								public const string FsimplefitterIcon = "assets/third party/fimpossible creations/plugins - animating/ground fitter/scripts/editor/resources/fsimplefitter icon.png";
							}
						}
					}
				}
			}
			public static class SharedTools
			{
				public static class Editor
				{
					public static class Resources
					{
						public const string TexHumanscaleref = "assets/third party/fimpossible creations/shared tools/editor/resources/tex_humanscaleref.png";

						public static class Fimp
						{
							public const string FimpColliderdataIcon = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/fimp_colliderdata icon.png";

							public static class Additional
							{
								public const string SprSearchdirectory = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/additional/spr_searchdirectory.png";
								public const string SprSearchnumeric = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/additional/spr_searchnumeric.png";
							}

							public static class Backgrounds
							{
								public const string FbgBox = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/backgrounds/fbgbox.png";
								public const string FButton = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/backgrounds/fbutton.png";
								public const string FButtonh = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/backgrounds/fbuttonh.png";
								public const string FButtonhover = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/backgrounds/fbuttonhover.png";
								public const string FButtonpress = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/backgrounds/fbuttonpress.png";
								public const string FFrameBox = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/backgrounds/fframebox.png";
								public const string FhelpBox = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/backgrounds/fhelpbox.png";
								public const string FhelpBoxh = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/backgrounds/fhelpboxh.png";
								public const string FinBox = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/backgrounds/finbox.png";
								public const string FinBoxh = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/backgrounds/finboxh.png";
								public const string FinBoxLight = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/backgrounds/finboxlight.png";
								public const string FviewBox = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/backgrounds/fviewbox.png";
							}

							public static class Icons
							{
								public const string Fadd = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/icons/fadd.png";
								public const string Fexport = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/icons/fexport.png";
								public const string Fexpose = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/icons/fexpose.png";
								public const string Fextension = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/icons/fextension.png";
								public const string Fgear = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/icons/fgear.png";
								public const string Fgearmain = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/icons/fgearmain.png";
								public const string Fgearsetup = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/icons/fgearsetup.png";
								public const string Fknob = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/icons/fknob.png";
								public const string Flimits = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/icons/flimits.png";
								public const string Fload = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/icons/fload.png";
								public const string Fmodule = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/icons/fmodule.png";
								public const string Foptimize = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/icons/foptimize.png";
								public const string Fphysics = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/icons/fphysics.png";
								public const string Frepair = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/icons/frepair.png";
								public const string Fsave = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/icons/fsave.png";
								public const string Fsliders = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/icons/fsliders.png";
								public const string Ftweaks = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/icons/ftweaks.png";
							}

							public static class MiscIcons
							{
								public const string Fabswitch = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/fabswitch.png";
								public const string FArrowDown = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/farrowdown.png";
								public const string FArrowleft = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/farrowleft.png";
								public const string FArrowright = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/farrowright.png";
								public const string FArrowup = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/farrowup.png";
								public const string Fdefault = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/fdefault.png";
								public const string Ffilter = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/ffilter.png";
								public const string Fgizmos = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/fgizmos.png";
								public const string Fgizmosoff = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/fgizmosoff.png";
								public const string Fgleftfolded = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/fgleftfolded.png";
								public const string Fgrightfolded = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/fgrightfolded.png";
								public const string Fgunfolded = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/fgunfolded.png";
								public const string Fgupfolded = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/fgupfolded.png";
								public const string Fhierarchyswitch = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/fhierarchyswitch.png";
								public const string Fjoy = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/fjoy.png";
								public const string Fleftfolded = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/fleftfolded.png";
								public const string Fmanual = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/fmanual.png";
								public const string Frandom = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/frandom.png";
								public const string Frect = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/frect.png";
								public const string Frightfolded = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/frightfolded.png";
								public const string Ftutorials = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/ftutorials.png";
								public const string Fundo = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/fundo.png";
								public const string Funfolded = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/funfolded.png";
								public const string Fupfolded = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/fupfolded.png";
								public const string Fwait = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/fwait.png";
								public const string FwebSite = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/fwebsite.png";
								public const string SprAxes = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/spr_axes.png";
								public const string SprDragbars = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/spr_dragbars.png";
								public const string SprFnote = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/spr_fnote.png";
								public const string SprIndenttreeline = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/spr_indenttreeline.png";
								public const string SprIndenttreelineh = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/spr_indenttreelineh.png";
								public const string SprListview = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/misc icons/spr_listview.png";
							}

							public static class SmallIcons
							{
								public const string Additional = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/additional.png";
								public const string Anchor = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/anchor.png";
								public const string Behaviour = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/behaviour.png";
								public const string Connections = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/connections.png";
								public const string Fagent = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/fagent.png";
								public const string Fanimator = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/fanimator.png";
								public const string Fbone = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/fbone.png";
								public const string Fcollider = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/fcollider.png";
								public const string Fcorrect = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/fcorrect.png";
								public const string Fcurve = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/fcurve.png";
								public const string Fcustomize = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/fcustomize.png";
								public const string Fdebug = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/fdebug.png";
								public const string Fdistance = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/fdistance.png";
								public const string Fdraganddrop = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/fdraganddrop.png";
								public const string FError = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/ferror.png";
								public const string Fhidden = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/fhidden.png";
								public const string Finfo = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/finfo.png";
								public const string Fmore = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/fmore.png";
								public const string Fmovement = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/fmovement.png";
								public const string Fprepare = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/fprepare.png";
								public const string Frefresh = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/frefresh.png";
								public const string FRemove = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/fremove.png";
								public const string FreName = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/frename.png";
								public const string Frotation = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/frotation.png";
								public const string Fwarning = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/fwarning.png";
								public const string Fwindow = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/fwindow.png";
								public const string Minigear = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/minigear.png";
								public const string Minimotion = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/minimotion.png";
								public const string Motion = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/motion.png";
								public const string Optimize = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/optimize.png";
								public const string Physics = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/physics.png";
								public const string Preview = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/preview.png";
								public const string Smallgear = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/smallgear.png";
								public const string Symmetry = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/symmetry.png";
								public const string Target = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/target.png";
								public const string Variables = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/variables.png";
								public const string Variables2 = "assets/third party/fimpossible creations/shared tools/editor/resources/fimp/small icons/variables2.png";
							}
						}
					}
				}
			}
		}

		public static class Kriptofx
		{
			public static class Explosions
			{
				public const string LightMap0CompLight = "assets/third party/kriptofx/explosions/scenes/pc_demo/lightmap-0_comp_light.exr";
				public const string PlatForm = "assets/third party/kriptofx/explosions/models/platform.png";

				public static class Textures
				{
					public const string Scenegrid = "assets/third party/kriptofx/explosions/textures/scene/scenegrid.png";

					public static class Explosions
					{
						public const string Explosion1 = "assets/third party/kriptofx/explosions/textures/explosions/explosion1.png";
						public const string Explosion10 = "assets/third party/kriptofx/explosions/textures/explosions/explosion10.png";
						public const string Explosion11 = "assets/third party/kriptofx/explosions/textures/explosions/explosion11.png";
						public const string Explosion12 = "assets/third party/kriptofx/explosions/textures/explosions/explosion12.png";
						public const string Explosion13 = "assets/third party/kriptofx/explosions/textures/explosions/explosion13.png";
						public const string Explosion14 = "assets/third party/kriptofx/explosions/textures/explosions/explosion14.png";
						public const string Explosion15 = "assets/third party/kriptofx/explosions/textures/explosions/explosion15.png";
						public const string Explosion16 = "assets/third party/kriptofx/explosions/textures/explosions/explosion16.png";
						public const string Explosion17 = "assets/third party/kriptofx/explosions/textures/explosions/explosion17.png";
						public const string Explosion18 = "assets/third party/kriptofx/explosions/textures/explosions/explosion18.png";
						public const string Explosion19 = "assets/third party/kriptofx/explosions/textures/explosions/explosion19.png";
						public const string Explosion2 = "assets/third party/kriptofx/explosions/textures/explosions/explosion2.png";
						public const string Explosion3 = "assets/third party/kriptofx/explosions/textures/explosions/explosion3.png";
						public const string Explosion4 = "assets/third party/kriptofx/explosions/textures/explosions/explosion4.png";
						public const string Explosion5 = "assets/third party/kriptofx/explosions/textures/explosions/explosion5.png";
						public const string Explosion6 = "assets/third party/kriptofx/explosions/textures/explosions/explosion6.png";
						public const string Explosion7 = "assets/third party/kriptofx/explosions/textures/explosions/explosion7.png";
						public const string Explosion8 = "assets/third party/kriptofx/explosions/textures/explosions/explosion8.png";
						public const string Explosion9 = "assets/third party/kriptofx/explosions/textures/explosions/explosion9.png";
					}

					public static class Models
					{
						public const string Stone1 = "assets/third party/kriptofx/explosions/textures/models/stone1.png";
						public const string Stone2 = "assets/third party/kriptofx/explosions/textures/models/stone2.png";
					}

					public static class Shared
					{
						public const string Distortiondiffuse = "assets/third party/kriptofx/explosions/textures/shared/distortiondiffuse.png";
						public const string Dudvheat = "assets/third party/kriptofx/explosions/textures/shared/dudvheat.png";
						public const string DudvMap = "assets/third party/kriptofx/explosions/textures/shared/dudvmap.png";

						public static class Particles
						{
							public const string Glow = "assets/third party/kriptofx/explosions/textures/shared/particles/glow.png";
							public const string Particletrail1 = "assets/third party/kriptofx/explosions/textures/shared/particles/particletrail1.png";
							public const string Randomparticlesalpha = "assets/third party/kriptofx/explosions/textures/shared/particles/randomparticlesalpha.png";
						}
					}

					public static class Trails
					{
						public const string Trail1 = "assets/third party/kriptofx/explosions/textures/trails/trail1.png";
						public const string Trail2 = "assets/third party/kriptofx/explosions/textures/trails/trail2.png";
						public const string Trail3 = "assets/third party/kriptofx/explosions/textures/trails/trail3.png";
						public const string Trail4 = "assets/third party/kriptofx/explosions/textures/trails/trail4.png";
						public const string Trail5 = "assets/third party/kriptofx/explosions/textures/trails/trail5.png";
						public const string Trail6 = "assets/third party/kriptofx/explosions/textures/trails/trail6.png";
					}
				}
			}
		}

		public static class Smaa
		{
			public static class Resources
			{
				public const string Areatex = "assets/third party/smaa/resources/areatex.tga";
				public const string Searchtex = "assets/third party/smaa/resources/searchtex.tga";
			}
		}

		public static class Vertextoolspro
		{
			public static class Resources
			{
				public static class Animator
				{
					public const string Background = "assets/third party/vertextoolspro/resources/animator/background.png";
					public const string Play = "assets/third party/vertextoolspro/resources/animator/play.png";
					public const string ToEnd = "assets/third party/vertextoolspro/resources/animator/to_end.png";
					public const string ToStart = "assets/third party/vertextoolspro/resources/animator/to_start.png";
					public const string VtpKeyFrameSelected = "assets/third party/vertextoolspro/resources/animator/vtp_keyframe_selected.png";
					public const string VtpKeyFrameUnselected = "assets/third party/vertextoolspro/resources/animator/vtp_keyframe_unselected.png";
					public const string VtpScroller = "assets/third party/vertextoolspro/resources/animator/vtp_scroller.png";
					public const string VtpSliderRed = "assets/third party/vertextoolspro/resources/animator/vtp_slider_red.png";
				}
				public static class Textures
				{
					public const string Bluechannelbg = "assets/third party/vertextoolspro/resources/textures/bluechannelbg.png";
					public const string Bluechannelbgpro = "assets/third party/vertextoolspro/resources/textures/bluechannelbgpro.png";
					public const string BoxBg = "assets/third party/vertextoolspro/resources/textures/box_bg.png";
					public const string Greenchannelbg = "assets/third party/vertextoolspro/resources/textures/greenchannelbg.png";
					public const string Greenchannelbgpro = "assets/third party/vertextoolspro/resources/textures/greenchannelbgpro.png";
					public const string Neutralbg = "assets/third party/vertextoolspro/resources/textures/neutralbg.png";
					public const string Neutralbgpro = "assets/third party/vertextoolspro/resources/textures/neutralbgpro.png";
					public const string Redchannelbg = "assets/third party/vertextoolspro/resources/textures/redchannelbg.png";
					public const string Redchannelbgpro = "assets/third party/vertextoolspro/resources/textures/redchannelbgpro.png";
				}
			}
		}

		public static class VolumetricLightbeam
		{
			public const string Dustparticles = "assets/third party/volumetriclightbeam/resources/dustparticles.psd";

			public static class Editor
			{
				public static class Icons
				{
					public const string Dynamicocclusion = "assets/third party/volumetriclightbeam/editor/icons/dynamicocclusion.png";
					public const string Floatingdustparticles = "assets/third party/volumetriclightbeam/editor/icons/floatingdustparticles.png";
					public const string TriggerZone = "assets/third party/volumetriclightbeam/editor/icons/triggerzone.png";
					public const string VolumetricLightbeam = "assets/third party/volumetriclightbeam/editor/icons/volumetriclightbeam.png";
				}
			}
		}
	}

}
