/*
* This file is auto-generated by AssetDump
* Do not edit manually
* Last updated: 08/13/2025 10:22:43
*/
// ReSharper disable MemberHidesStaticFromOuterClass
namespace Oxide.Ext.UiFramework.Constants;

public static class UiTextures
{
	public static class Content
	{
		public const string CobaltLogistics = "assets/content/structures/coaling_tower/textures/cobalt_logistics.tga";
		public const string Island = "assets/content/nexus/island/island.png";

		public static class Building
		{
			public static class BasicGeo
			{
				public static class Materials
				{
					public const string DestroyOverlay = "assets/content/building/basicgeo/materials/destroyoverlay.tga";
					public const string Guide = "assets/content/building/basicgeo/materials/guide.tga";
					public const string GuideInvalid = "assets/content/building/basicgeo/materials/guideinvalid.tga";
					public const string LevelFrame = "assets/content/building/basicgeo/materials/levelframe.tga";
					public const string LevelMetal = "assets/content/building/basicgeo/materials/levelmetal.tga";
					public const string LevelMetalAdv = "assets/content/building/basicgeo/materials/levelmetaladv.tga";
					public const string LevelStone = "assets/content/building/basicgeo/materials/levelstone.tga";
					public const string LevelStoneAdv = "assets/content/building/basicgeo/materials/levelstoneadv.tga";
					public const string LevelWood = "assets/content/building/basicgeo/materials/levelwood.tga";
					public const string LevelWoodAdv = "assets/content/building/basicgeo/materials/levelwoodadv.tga";
				}
			}
			public static class Parts
			{
				public static class InteriorSkins
				{
					public static class Textures
					{
						public const string CarpetMask = "assets/content/building/parts/interior_skins/textures/carpet_mask.tga";
						public const string FloorCarpetADiff = "assets/content/building/parts/interior_skins/textures/floor_carpet_a_diff.tga";
						public const string FloorCarpetBDiff = "assets/content/building/parts/interior_skins/textures/floor_carpet_b_diff.tga";
						public const string FloorCarpetCDiff = "assets/content/building/parts/interior_skins/textures/floor_carpet_c_diff.tga";
					}
				}
			}
		}

		public static class Decals
		{
			public const string DecalBlood = "assets/content/decals/decalblood.tga";
			public const string DecalBloodSpecGloss = "assets/content/decals/decalblood-specgloss.tga";
			public const string DecalBloodSplatter01Albedo = "assets/content/decals/decal_blood_splatter_01_albedo.tga";
			public const string DecalBloodSplatter02Albedo = "assets/content/decals/decal_blood_splatter_02_albedo.tga";
			public const string DecalBloodSplatter03Albedo = "assets/content/decals/decal_blood_splatter_03_albedo.tga";
			public const string DecalBluntImpact01Albedo = "assets/content/decals/decal_blunt_impact_01_albedo.tga";
			public const string DecalBulletDirtAlbedo01 = "assets/content/decals/decal_bullet_dirt_albedo_01.tga";
			public const string DecalBulletDirtSpecular01 = "assets/content/decals/decal_bullet_dirt_specular_01.tga";
			public const string DecalBulletFleshEntry01Albedo = "assets/content/decals/decal_bullet_flesh_entry_01_albedo.tga";
			public const string DecalBulletFleshExit01Albedo = "assets/content/decals/decal_bullet_flesh_exit_01_albedo.tga";
			public const string DecalBulletForestAlbedo01 = "assets/content/decals/decal_bullet_forest_albedo_01.tga";
			public const string DecalBulletGlass2Albedo = "assets/content/decals/decal_bullet_glass2_albedo.tga";
			public const string DecalBulletGlass3Albedo = "assets/content/decals/decal_bullet_glass3_albedo.tga";
			public const string DecalBulletGlassAlbedo = "assets/content/decals/decal_bullet_glass_albedo.tga";
			public const string DecalBulletHole01 = "assets/content/decals/decalbullethole01.tga";
			public const string DecalBulletHole02 = "assets/content/decals/decalbullethole02.tga";
			public const string DecalBulletHole03 = "assets/content/decals/decalbullethole03.tga";
			public const string DecalBulletHole04 = "assets/content/decals/decalbullethole04.tga";
			public const string DecalBulletHole05 = "assets/content/decals/decalbullethole05.tga";
			public const string DecalBulletHoleMetal01 = "assets/content/decals/decalbulletholemetal01.tga";
			public const string DecalBulletHoleWood01 = "assets/content/decals/decalbulletholewood01.tga";
			public const string DecalBulletHoleWood02 = "assets/content/decals/decalbulletholewood02.tga";
			public const string DecalBulletHoleWood03 = "assets/content/decals/decalbulletholewood03.tga";
			public const string DecalBulletHoleWood04 = "assets/content/decals/decalbulletholewood04.tga";
			public const string DecalBulletImpactTundra01 = "assets/content/decals/decal_bullet_impact_tundra_01.tga";
			public const string DecalBulletMetal01Albedo = "assets/content/decals/decal_bullet_metal_01_albedo.tga";
			public const string DecalBulletMetal02Albedo = "assets/content/decals/decal_bullet_metal_02_albedo.tga";
			public const string DecalBulletMetal03Albedo = "assets/content/decals/decal_bullet_metal_03_albedo.tga";
			public const string DecalBulletRoadAlbedo01 = "assets/content/decals/decal_bullet_road_albedo_01.tga";
			public const string DecalBulletSand01Albedo = "assets/content/decals/decal_bullet_sand_01_albedo.tga";
			public const string DecalBulletSandBagAlbedo = "assets/content/decals/decal_bullet_sandbag_albedo.tga";
			public const string DecalBulletSnow01Albedo = "assets/content/decals/decal_bullet_snow_01_albedo.tga";
			public const string DecalBulletStone01Albedo = "assets/content/decals/decal_bullet_stone_01_albedo.tga";
			public const string DecalExplosion = "assets/content/decals/decal_explosion.tga";
			public const string DecalExplosion01 = "assets/content/decals/decalexplosion01.tga";
			public const string DecalFootprintHumanBareSandLeftAlbedo = "assets/content/decals/decal_footprint_human_bare_sand_left_albedo.tga";
			public const string DecalFootprintHumanBareSandRightAlbedo = "assets/content/decals/decal_footprint_human_bare_sand_right_albedo.tga";
			public const string DecalFootprintHumanBareSnowLeftAlbedo = "assets/content/decals/decal_footprint_human_bare_snow_left_albedo.tga";
			public const string DecalFootprintHumanBareSnowRightAlbedo = "assets/content/decals/decal_footprint_human_bare_snow_right_albedo.tga";
			public const string DecalFootprintHumanBootSandLeftAlbedo = "assets/content/decals/decal_footprint_human_boot_sand_left_albedo.tga";
			public const string DecalFootprintHumanBootSandRightAlbedo = "assets/content/decals/decal_footprint_human_boot_sand_right_albedo.tga";
			public const string DecalFootprintHumanBootSnowLeftAlbedo = "assets/content/decals/decal_footprint_human_boot_snow_left_albedo.tga";
			public const string DecalFootprintHumanBootSnowRightAlbedo = "assets/content/decals/decal_footprint_human_boot_snow_right_albedo.tga";
			public const string DecalRifleBulletImpactMetalAAlbedo = "assets/content/decals/decal_rifle_bullet_impact_metal_a_albedo.tga";
			public const string DecalStabFlesh01Albedo = "assets/content/decals/decal_stab_flesh_01_albedo.tga";
			public const string DecalXSprayA = "assets/content/decals/decal_xspray_a.png";
			public const string DecalXSprayARed = "assets/content/decals/decal_xspray_a_red.tga";
		}

		public static class Developer
		{
			public const string DevError = "assets/content/developer/deverror.png";
			public const string DevGrey = "assets/content/developer/devgrey.png";
			public const string DevWhite = "assets/content/developer/devwhite.png";
		}

		public static class Effects
		{
			public const string Twinkle = "assets/content/effects/explosions/textures/twinkle.png";

			public static class Crossbreed
			{
				public const string FxCircle = "assets/content/effects/crossbreed/fx circle.png";
				public const string FxGradientSkewed = "assets/content/effects/crossbreed/fx gradient skewed.png";
			}

			public static class Textures
			{
				public static class Clouds
				{
					public const string HorizonCumulas01Albedo = "assets/content/effects/textures/clouds/horizon_cumulas_01_albedo.tga";
					public const string HorizonCumulas02Albedo = "assets/content/effects/textures/clouds/horizon_cumulas_02_albedo.tga";
					public const string HorizonCumulas03Albedo = "assets/content/effects/textures/clouds/horizon_cumulas_03_albedo.tga";
					public const string LargeCirrus01Albedo = "assets/content/effects/textures/clouds/large_cirrus_01_albedo.tga";
					public const string LargeCirrus02Albedo = "assets/content/effects/textures/clouds/large_cirrus_02_albedo.tga";
					public const string LargeCirrus03Albedo = "assets/content/effects/textures/clouds/large_cirrus_03_albedo.tga";
					public const string LargeCirrus04Albedo = "assets/content/effects/textures/clouds/large_cirrus_04_albedo.tga";
					public const string LargeCirrus05Albedo = "assets/content/effects/textures/clouds/large_cirrus_05_albedo.tga";
					public const string LargeCumulas01Albedo = "assets/content/effects/textures/clouds/large_cumulas_01_albedo.tga";
					public const string LargeCumulas02Albedo = "assets/content/effects/textures/clouds/large_cumulas_02_albedo.tga";
					public const string LargeCumulas03Albedo = "assets/content/effects/textures/clouds/large_cumulas_03_albedo.tga";
					public const string SingleCumulas01Albedo = "assets/content/effects/textures/clouds/single_cumulas_01_albedo.tga";
					public const string SingleCumulas02Albedo = "assets/content/effects/textures/clouds/single_cumulas_02_albedo.tga";
					public const string SingleCumulas03Albedo = "assets/content/effects/textures/clouds/single_cumulas_03_albedo.tga";
					public const string SingleCumulas04Albedo = "assets/content/effects/textures/clouds/single_cumulas_04_albedo.tga";
					public const string SingleCumulas05Albedo = "assets/content/effects/textures/clouds/single_cumulas_05_albedo.tga";
					public const string StratoCumulus02Albedo = "assets/content/effects/textures/clouds/stratocumulus_02_albedo.tga";
					public const string TransitionAltoStratus06Albedo = "assets/content/effects/textures/clouds/transition_altostratus_06_albedo.tga";
				}
				public static class Sand
				{
					public const string DecalParticleSoft = "assets/content/effects/textures/sand/decal_particle_soft.psd";
					public const string DecalSand2 = "assets/content/effects/textures/sand/decal_sand2.psd";
					public const string FxGradient = "assets/content/effects/textures/sand/fx_gradient.psd";
					public const string FxGradientSoftBottom = "assets/content/effects/textures/sand/fx_gradient_softbottom.psd";
					public const string SandParticleA = "assets/content/effects/textures/sand/sand_particle_a.tga";
				}
				public static class Smoke
				{
					public const string ExplosionCoreSmoke = "assets/content/effects/textures/smoke/explosion_core_smoke.png";
					public const string FrostyBreath = "assets/content/effects/textures/smoke/frosty_breath.tga";
					public const string Wispy4 = "assets/content/effects/textures/smoke/wispy-4.tga";
				}
			}
		}

		public static class Materials
		{
			public const string Cable = "assets/content/materials/cable.jpg";
			public const string HighLight = "assets/content/materials/highlight.png";
			public const string HighLight2 = "assets/content/materials/highlight2.png";
		}

		public static class Nature
		{
			public static class Terrain
			{
				public static class Misc
				{
					public const string NoisePerlin = "assets/content/nature/terrain/misc/noise_perlin.tga";
					public const string NoiseWhite = "assets/content/nature/terrain/misc/noise_white.tga";
					public const string TerrainPotatoDetail = "assets/content/nature/terrain/misc/terrain_potato_detail.png";
				}
			}
		}

		public static class Player
		{
			public static class Clothing
			{
				public const string KnittedDetailDiff = "assets/content/player/clothing/basic/materials/knitted/knitteddetail_diff.png";

				public static class TilingTextures
				{
					public const string CamoTiling01Tint = "assets/content/player/clothing/tiling_textures/camo_tiling_01_tint.tga";
					public const string CamoTilingMuricaTint = "assets/content/player/clothing/tiling_textures/camo_tiling_murica_tint.tga";
					public const string CamoTilingSovietTint = "assets/content/player/clothing/tiling_textures/camo_tiling_soviet_tint.tga";
					public const string ClothTiling01Color = "assets/content/player/clothing/tiling_textures/cloth_tiling_01_color.tga";
					public const string ClothTiling01Fuzz = "assets/content/player/clothing/tiling_textures/cloth_tiling_01_fuzz.tga";
					public const string ClothTiling02Color = "assets/content/player/clothing/tiling_textures/cloth_tiling_02_color.tga";
					public const string ClothTiling02Fuzz = "assets/content/player/clothing/tiling_textures/cloth_tiling_02_fuzz.tga";
					public const string ClothTiling03Color = "assets/content/player/clothing/tiling_textures/cloth_tiling_03_color.tga";
					public const string GenericTilingFuzz = "assets/content/player/clothing/tiling_textures/generic_tiling_fuzz.tga";
				}
			}
		}

		public static class Props
		{
			public static class LightFixtures
			{
				public static class V2
				{
					public static class Ies
					{
						public static class SpotLight
						{
							public const string IesCookieHemisphereSpot = "assets/content/props/light_fixtures/v2/ies/spotlight/ies-cookie-hemisphere-spot.tga";
							public const string IesCookieReflector1 = "assets/content/props/light_fixtures/v2/ies/spotlight/ies-cookie-reflector1.tga";
							public const string IesCookieReflector2 = "assets/content/props/light_fixtures/v2/ies/spotlight/ies-cookie-reflector2.tga";
							public const string IesCookieReflector3 = "assets/content/props/light_fixtures/v2/ies/spotlight/ies-cookie-reflector3.tga";
							public const string IesCookieReflector4 = "assets/content/props/light_fixtures/v2/ies/spotlight/ies-cookie-reflector4.tga";
							public const string IesCookieReflector5 = "assets/content/props/light_fixtures/v2/ies/spotlight/ies-cookie-reflector5.tga";
						}
					}
				}
			}
			public static class Paintings
			{
				public static class Textures
				{
					public const string LandscapeCity = "assets/content/props/paintings/textures/landscape_city.tga";
					public const string LandscapeMountains = "assets/content/props/paintings/textures/landscape_mountains.tga";
					public const string LandscapeStrangePainting = "assets/content/props/paintings/textures/landscape_strange_painting.tga";
					public const string PortraitFamilly = "assets/content/props/paintings/textures/portrait_familly.tga";
					public const string PortraitManTractor = "assets/content/props/paintings/textures/portrait_man_tractor.tga";
				}
			}
		}

		public static class Shaders
		{
			public static class Resources
			{
				public static class Textures
				{
					public const string BlueNoise32 = "assets/content/shaders/resources/textures/bluenoise_32.png";
					public const string Envbrdflut = "assets/content/shaders/resources/textures/envbrdflut.png";
					public const string Noise2dHf64 = "assets/content/shaders/resources/textures/noise2d_hf_64.png";
					public const string PfgdGgx = "assets/content/shaders/resources/textures/pfgd_ggx.exr";
					public const string SkinH = "assets/content/shaders/resources/textures/skin_h.tga";
					public const string SkinN = "assets/content/shaders/resources/textures/skin_n.tga";
				}
			}
		}

		public static class Textures
		{
			public static class Debug
			{
				public const string MacbethChart = "assets/content/textures/debug/macbeth_chart.png";
				public const string MetalGradient = "assets/content/textures/debug/metal_gradient.tga";
			}
			public static class Decals
			{
				public const string ArrowStraightA = "assets/content/textures/decals/arrow_straight_a.tga";
				public const string ChillZone = "assets/content/textures/decals/chillzone.png";
				public const string CompoundSigns = "assets/content/textures/decals/compound_signs.tga";
				public const string ConcreteCracksA = "assets/content/textures/decals/concrete_cracks_a.tga";
				public const string ConcreteLeaksA = "assets/content/textures/decals/concrete_leaks_a.tga";
				public const string ConcreteLeaksB = "assets/content/textures/decals/concrete_leaks_b.tga";
				public const string ConcreteLeaksC = "assets/content/textures/decals/concrete_leaks_c.tga";
				public const string ConcreteLeaksD = "assets/content/textures/decals/concrete_leaks_d.tga";
				public const string ConcreteLeaksE = "assets/content/textures/decals/concrete_leaks_e.tga";
				public const string ConcreteLeaksF = "assets/content/textures/decals/concrete_leaks_f.tga";
				public const string DecalVertiigoGraffiti = "assets/content/textures/decals/decal_vertiigo_graffiti.png";
				public const string Kargo1X4 = "assets/content/textures/decals/kargo_1x4.tga";
				public const string KeepOut = "assets/content/textures/decals/keep_out.tga";
				public const string LabelOilA = "assets/content/textures/decals/label_oil_a.tga";
				public const string RoadDebris = "assets/content/textures/decals/road_debris.tga";
				public const string RustMillsShipping = "assets/content/textures/decals/rust_mills_shipping.tga";
				public const string SeaweedPlaneSeaweedDecalAlbedoTransparency = "assets/content/textures/decals/seaweedplane_seaweeddecal_albedotransparency.tga";
				public const string SeaweedPlaneSeaweedDecalMetallicSmoothness = "assets/content/textures/decals/seaweedplane_seaweeddecal_metallicsmoothness.tga";
				public const string SeaweedPlaneSeaweedDecalTransmission = "assets/content/textures/decals/seaweedplane_seaweeddecal_transmission.tga";
				public const string StranglerFigWallDecalDiff = "assets/content/textures/decals/strangler_fig_wall_decal_diff.tga";
				public const string WarningBiohazardA = "assets/content/textures/decals/warning_biohazard_a.tga";
				public const string WarningExplosiveA = "assets/content/textures/decals/warning_explosive_a.tga";
				public const string WarningFuelA = "assets/content/textures/decals/warning_fuel_a.tga";
				public const string WarningNonHazardous = "assets/content/textures/decals/warning_non_hazardous.png";
				public const string WarningPoison = "assets/content/textures/decals/warning_poison.png";
				public const string WarningRadioactiveA = "assets/content/textures/decals/warning_radioactive_a.tga";
				public const string WarningRecycle1 = "assets/content/textures/decals/warning_recycle_1.png";
				public const string WarningVolatile = "assets/content/textures/decals/warning_volatile.png";
			}
			public static class Detail
			{
				public const string AsphaltADetail = "assets/content/textures/detail/asphalt_a_detail.tga";
				public const string ConcreteADetail = "assets/content/textures/detail/concrete_a_detail.tga";
				public const string ConcreteBDetail = "assets/content/textures/detail/concrete_b_detail.tga";
				public const string FabricADetail = "assets/content/textures/detail/fabric_a_detail.tga";
				public const string GenericMask1 = "assets/content/textures/detail/generic_mask1.tga";
				public const string MetalADetail = "assets/content/textures/detail/metal_a_detail.tga";
				public const string MetalCDetail = "assets/content/textures/detail/metal_c_detail.tga";
				public const string MetalDDetail = "assets/content/textures/detail/metal_d_detail.tga";
				public const string PlasterADetail = "assets/content/textures/detail/plaster_a_detail.tga";
				public const string PlasterBDetail = "assets/content/textures/detail/plaster_b_detail.tga";
				public const string RandomColorADetail = "assets/content/textures/detail/random_color_a_detail.tga";
				public const string RandomColorADetailMask = "assets/content/textures/detail/random_color_a_detail_mask.tga";
				public const string RustADetail = "assets/content/textures/detail/rust_a_detail.tga";
				public const string RustBDetail = "assets/content/textures/detail/rust_b_detail.tga";
				public const string RustCDetail = "assets/content/textures/detail/rust_c_detail.tga";
			}
		}

		public static class Ui
		{
			public const string MugshotUnknown = "assets/content/ui/mugshot_unknown.png";
			public const string NmsDirt = "assets/content/ui/nms-dirt.png";
			public const string OverlayBleeding = "assets/content/ui/overlay_bleeding.png";
			public const string UiGradientDownTight = "assets/content/ui/ui.gradient.down.tight.psd";
			public const string UiSpashScreen = "assets/content/ui/ui.spashscreen.psd";

			public static class GameUi
			{
				public const string UiCrosshairCircle = "assets/content/ui/gameui/ui.crosshair.circle.png";

				public static class AttackHeli
				{
					public static class Compass
					{
						public const string CompassStrip = "assets/content/ui/gameui/attackheli/compass/compass_strip.psd";
						public const string CompassStrip2 = "assets/content/ui/gameui/attackheli/compass/compass_strip_2.psd";
						public const string CompassStripDigital = "assets/content/ui/gameui/attackheli/compass/compass_strip_digital.psd";
					}
				}

				public static class CardGames
				{
					public static class Deck
					{
						public static class Jokers
						{
							public const string JokerBlack = "assets/content/ui/gameui/cardgames/deck/jokers/joker_black.png";
							public const string JokerMixed = "assets/content/ui/gameui/cardgames/deck/jokers/joker_mixed.png";
							public const string JokerRed = "assets/content/ui/gameui/cardgames/deck/jokers/joker_red.png";
						}
					}
				}
			}
		}

		public static class Vehicles
		{
			public static class ModularCar
			{
				public static class Models
				{
					public static class Materials
					{
						public static class Textures
						{
							public const string CheckEngineLight = "assets/content/vehicles/modularcar/models/materials/textures/checkenginelight.tga";
							public const string LowGasLight = "assets/content/vehicles/modularcar/models/materials/textures/lowgaslight.tga";
						}
					}
				}
			}
		}
	}
	public static class Icons
	{
		public const string CircleGradientWhite = "assets/icons/circle_gradient_white.png";
		public const string CursorHand = "assets/icons/cursor-hand.png";
		public const string GestureRaiseTheRoofAlternative = "assets/icons/gestures/gesture-raise-the-roof-alternative.png";
		public const string Grenade = "assets/icons/grenade.png";
		public const string SteamInventory = "assets/icons/steam_inventory.png";
	}
	public static class Prefabs
	{
		public const string HolosightReticleStandard = "assets/prefabs/weapon mods/holosight/holosight.reticle.standard.png";
		public const string MissionIconComplete = "assets/prefabs/missions/textures/mission_icon_complete.png";
		public const string ReclaimStencil = "assets/prefabs/gamemodes/objects/reclaim/materials/reclaim_stencil.png";

		public static class Tools
		{
			public static class SprayCan
			{
				public static class Sprays
				{
					public const string BeanCan = "assets/prefabs/tools/spraycan/sprays/bean_can.png";
					public const string CandleHat = "assets/prefabs/tools/spraycan/sprays/candle_hat.png";
					public const string FacepunchLogo = "assets/prefabs/tools/spraycan/sprays/facepunch_logo.png";
					public const string FrogBoot = "assets/prefabs/tools/spraycan/sprays/frog_boot.png";
					public const string Hazmat = "assets/prefabs/tools/spraycan/sprays/hazmat.png";
					public const string Rock = "assets/prefabs/tools/spraycan/sprays/rock.png";
					public const string RustLogo = "assets/prefabs/tools/spraycan/sprays/rust_logo.png";
					public const string Target = "assets/prefabs/tools/spraycan/sprays/target.png";
					public const string WhensWhip = "assets/prefabs/tools/spraycan/sprays/whens_whip.png";

					public static class Skins
					{
						public static class JungleDlc
						{
							public static class Static
							{
								public static class Materials
								{
									public const string JungleSkull = "assets/prefabs/tools/spraycan/sprays/skins/jungledlc/static/materials/jungle_skull.png";
									public const string JungleTiger = "assets/prefabs/tools/spraycan/sprays/skins/jungledlc/static/materials/jungle_tiger.png";
								}
							}
						}
					}
				}
			}
		}

		public static class WallPaper
		{
			public static class Models
			{
				public static class Textures
				{
					public const string BlueDiamondWallPaperADiff = "assets/prefabs/wallpaper/models/textures/blue_diamond_wallpaper_a_diff.tga";
					public const string GlowBoardWallPaperADiff = "assets/prefabs/wallpaper/models/textures/glowboard_wallpaper_a_diff.tga";
					public const string GlowBoardWallPaperAEmissive = "assets/prefabs/wallpaper/models/textures/glowboard_wallpaper_a_emissive.tga";
					public const string GlowBoardWallPaperBDiff = "assets/prefabs/wallpaper/models/textures/glowboard_wallpaper_b_diff.tga";
					public const string GlowBoardWallPaperBEmissive = "assets/prefabs/wallpaper/models/textures/glowboard_wallpaper_b_emissive.tga";
					public const string SubwayWallPaperADiff = "assets/prefabs/wallpaper/models/textures/subway_wallpaper_a_diff.tga";
					public const string SubwayWallPaperBDiff = "assets/prefabs/wallpaper/models/textures/subway_wallpaper_b_diff.tga";
					public const string VintageWallPaperADiff = "assets/prefabs/wallpaper/models/textures/vintage_wallpaper_a_diff.tga";
					public const string VintageWallPaperAMask = "assets/prefabs/wallpaper/models/textures/vintage_wallpaper_a_mask.tga";
					public const string VintageWallPaperBDiff = "assets/prefabs/wallpaper/models/textures/vintage_wallpaper_b_diff.tga";
					public const string VintageWallPaperCDiff = "assets/prefabs/wallpaper/models/textures/vintage_wallpaper_c_diff.tga";
					public const string VintageWallPaperDDiff = "assets/prefabs/wallpaper/models/textures/vintage_wallpaper_d_diff.tga";
					public const string WainscottingWallPaperADiff = "assets/prefabs/wallpaper/models/textures/wainscotting_wallpaper_a_diff.tga";
					public const string WainscottingWallPaperBDiff = "assets/prefabs/wallpaper/models/textures/wainscotting_wallpaper_b_diff.tga";
					public const string WainscottingWallPaperCDiff = "assets/prefabs/wallpaper/models/textures/wainscotting_wallpaper_c_diff.tga";
					public const string WallPaperClouds1Diff = "assets/prefabs/wallpaper/models/textures/wallpaper_clouds_1_diff.tga";
					public const string WallPaperGeometric2Diff = "assets/prefabs/wallpaper/models/textures/wallpaper_geometric_2_diff.tga";
					public const string WallPaperGeometric3Diff = "assets/prefabs/wallpaper/models/textures/wallpaper_geometric_3_diff.tga";
					public const string WallPaperPolka1Diff = "assets/prefabs/wallpaper/models/textures/wallpaper_polka_1_diff.tga";
					public const string WallPaperPolka2Diff = "assets/prefabs/wallpaper/models/textures/wallpaper_polka_2_diff.tga";
					public const string WallPaperPolka3Diff = "assets/prefabs/wallpaper/models/textures/wallpaper_polka_3_diff.tga";
					public const string WallPaperRetro1Diff = "assets/prefabs/wallpaper/models/textures/wallpaper_retro_1_diff.tga";
					public const string WallPaperRetro2Diff = "assets/prefabs/wallpaper/models/textures/wallpaper_retro_2_diff.tga";
					public const string WallPaperRetro3Diff = "assets/prefabs/wallpaper/models/textures/wallpaper_retro_3_diff.tga";
					public const string WallPaperRoyal1Diff = "assets/prefabs/wallpaper/models/textures/wallpaper_royal_1_diff.tga";
					public const string WallPaperRoyal2Diff = "assets/prefabs/wallpaper/models/textures/wallpaper_royal_2_diff.tga";
					public const string WallPaperRoyal3Diff = "assets/prefabs/wallpaper/models/textures/wallpaper_royal_3_diff.tga";
					public const string WallPaperVenetianPlasterADiff = "assets/prefabs/wallpaper/models/textures/wallpaper_venetian_plaster_a_diff.tga";
					public const string WallPaperVenetianPlasterBDiff = "assets/prefabs/wallpaper/models/textures/wallpaper_venetian_plaster_b_diff.tga";
					public const string WallPaperVenetianPlasterCDiff = "assets/prefabs/wallpaper/models/textures/wallpaper_venetian_plaster_c_diff.tga";
					public const string YellowStripeWallPaperADiff = "assets/prefabs/wallpaper/models/textures/yellow_stripe_wallpaper_a_diff.tga";

					public static class JungleDlc
					{
						public const string JungleDlcAnimalsAlbedo = "assets/prefabs/wallpaper/models/textures/jungle_dlc/jungledlc_animals.albedo.tga";
						public const string JungleDlcAnimalsAo = "assets/prefabs/wallpaper/models/textures/jungle_dlc/jungledlc_animals.ao.tga";
						public const string JungleDlcAnimalsNormal = "assets/prefabs/wallpaper/models/textures/jungle_dlc/jungledlc_animals.normal.tga";
						public const string JungleDlcAnimalsSpecGloss = "assets/prefabs/wallpaper/models/textures/jungle_dlc/jungledlc_animals.specgloss.tga";
						public const string JungleDlcLeavesAlbedo = "assets/prefabs/wallpaper/models/textures/jungle_dlc/jungledlc_leaves.albedo.tga";
						public const string JungleDlcLeavesAo = "assets/prefabs/wallpaper/models/textures/jungle_dlc/jungledlc_leaves.ao.tga";
						public const string JungleDlcLeavesNormal = "assets/prefabs/wallpaper/models/textures/jungle_dlc/jungledlc_leaves.normal.tga";
						public const string JungleDlcLeavesSpecGloss = "assets/prefabs/wallpaper/models/textures/jungle_dlc/jungledlc_leaves.specgloss.tga";
						public const string JungleDlcSigilAlbedo = "assets/prefabs/wallpaper/models/textures/jungle_dlc/jungledlc_sigil.albedo.tga";
						public const string JungleDlcSigilAo = "assets/prefabs/wallpaper/models/textures/jungle_dlc/jungledlc_sigil.ao.tga";
						public const string JungleDlcSigilNormal = "assets/prefabs/wallpaper/models/textures/jungle_dlc/jungledlc_sigil.normal.tga";
						public const string JungleDlcSigilSpecGloss = "assets/prefabs/wallpaper/models/textures/jungle_dlc/jungledlc_sigil.specgloss.tga";
					}

					public static class Lny25
					{
						public const string Lny25BambooLayeredDiff = "assets/prefabs/wallpaper/models/textures/lny25/lny25_bamboo_layered_diff.tga";
						public const string Lny25CherryBlossomsDiff = "assets/prefabs/wallpaper/models/textures/lny25/lny25_cherry_blossoms_diff.tga";
						public const string Lny25ChineseLanternsDiff = "assets/prefabs/wallpaper/models/textures/lny25/lny25_chinese_lanterns_diff.tga";
						public const string Lny25DiamondsDiff = "assets/prefabs/wallpaper/models/textures/lny25/lny25_diamonds_diff.tga";
						public const string Lny25PanelADiff = "assets/prefabs/wallpaper/models/textures/lny25/lny25_panel_a_diff.tga";
						public const string Lny25PanelBDiff = "assets/prefabs/wallpaper/models/textures/lny25/lny25_panel_b_diff.tga";
						public const string Lny25PanelCDiff = "assets/prefabs/wallpaper/models/textures/lny25/lny25_panel_c_diff.tga";
					}

					public static class StarterPackFloorCeiling
					{
						public const string CeilingArtexSwirlsDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_artex_swirls_diff.tga";
						public const string CeilingArtexWavesDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_artex_waves_diff.tga";
						public const string CeilingMetalSheetADiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_metal_sheet_a_diff.tga";
						public const string CeilingMetalSheetBDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_metal_sheet_b_diff.tga";
						public const string CeilingMetalSheetCDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_metal_sheet_c_diff.tga";
						public const string CeilingOfficeDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_office_diff.tga";
						public const string CeilingParquetCDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_parquet_c_diff.tga";
						public const string CeilingParquetPaintedABlue02Diff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_parquet_painted_a_blue_02_diff.tga";
						public const string CeilingParquetPaintedABlueDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_parquet_painted_a_blue_diff.tga";
						public const string CeilingParquetPaintedADiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_parquet_painted_a_diff.tga";
						public const string CeilingParquetPaintedAGreenDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_parquet_painted_a_green_diff.tga";
						public const string CeilingParquetPaintedAPinkDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_parquet_painted_a_pink_diff.tga";
						public const string CeilingParquetPaintedAYellowDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_parquet_painted_a_yellow_diff.tga";
						public const string CeilingPlasterBoardADiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_plasterboard_a_diff.tga";
						public const string CeilingPlasterDamagedBlueDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_plaster_damaged_blue_diff.tga";
						public const string CeilingPlasterDamagedGreenDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_plaster_damaged_green_diff.tga";
						public const string CeilingSubwayADiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_subway_a_diff.tga";
						public const string CeilingSubwayAPatternDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_subway_a_pattern_diff.tga";
						public const string CeilingSubwayAYellowDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_subway_a_yellow_diff.tga";
						public const string CeilingSubwayBDiffuse = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_subway_b_diffuse.tga";
						public const string CeilingSubwayBPatternDiffuse = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_subway_b_pattern_diffuse.tga";
						public const string CeilingWoodBeamsADiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/ceiling_woodbeams_a_diff.tga";
						public const string FloorAsbestosTilesADiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_asbestos_tiles_a_diff.tga";
						public const string FloorAsbestosTilesBDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_asbestos_tiles_b_diff.tga";
						public const string FloorAsbestosTilesCDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_asbestos_tiles_c_diff.tga";
						public const string FloorAsbestosTilesDDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_asbestos_tiles_d_diff.tga";
						public const string FloorAsbestosTilesVintageCDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_asbestos_tiles_vintage_c_diff.tga";
						public const string FloorAsbestosTilesVintageDDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_asbestos_tiles_vintage_d_diff.tga";
						public const string FloorCarpetADiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_carpet_a_diff.tga";
						public const string FloorCarpetBDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_carpet_b_diff.tga";
						public const string FloorCarpetPlainADiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_carpet_plain_a_diff.tga";
						public const string FloorCarpetPlainBDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_carpet_plain_b_diff.tga";
						public const string FloorMarbleADiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_marble_a_diff.tga";
						public const string FloorMarbleBDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_marble_b_diff.tga";
						public const string FloorMetalTreadplateADiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_metal_treadplate_a_diff.tga";
						public const string FloorParquetADiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_parquet_a_diff.tga";
						public const string FloorParquetBDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_parquet_b_diff.tga";
						public const string FloorParquetCDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_parquet_c_diff.tga";
						public const string FloorParquetDDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_parquet_d_diff.tga";
						public const string FloorParquetPaintedADiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_parquet_painted_a_diff.tga";
						public const string FloorParquetPaintedBBlueDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_parquet_painted_b_blue_diff.tga";
						public const string FloorParquetPaintedBDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_parquet_painted_b_diff.tga";
						public const string FloorParquetPaintedCDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_parquet_painted_c_diff.tga";
						public const string FloorParquetPaintedDDiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_parquet_painted_d_diff.tga";
						public const string FloorTatamiADiff = "assets/prefabs/wallpaper/models/textures/starter_pack_floor_ceiling/floor_tatami_a_diff.tga";
					}

					public static class WallPaperTools
					{
						public const string CeilingPaperDiffuse = "assets/prefabs/wallpaper/models/textures/wallpaper_tools/ceilingpaper_diffuse.tga";
						public const string CeilingPaperMask = "assets/prefabs/wallpaper/models/textures/wallpaper_tools/ceilingpaper_mask.tga";
						public const string CeilingPaperSpecGloss = "assets/prefabs/wallpaper/models/textures/wallpaper_tools/ceilingpaper_specgloss.tga";
						public const string FloorPaperToolDiffuse = "assets/prefabs/wallpaper/models/textures/wallpaper_tools/floorpaper_tool_diffuse.tga";
						public const string FloorPaperToolMask = "assets/prefabs/wallpaper/models/textures/wallpaper_tools/floorpaper_tool_mask.tga";
						public const string FloorPaperToolSpeGloss = "assets/prefabs/wallpaper/models/textures/wallpaper_tools/floorpaper_tool_spegloss.tga";
						public const string WallPaperRollDiffuse = "assets/prefabs/wallpaper/models/textures/wallpaper_tools/wallpaper_roll_diffuse.tga";
						public const string WallPaperRollMask = "assets/prefabs/wallpaper/models/textures/wallpaper_tools/wallpaper_roll_mask.tga";
						public const string WallPaperRollSpecGloss = "assets/prefabs/wallpaper/models/textures/wallpaper_tools/wallpaper_roll_specgloss.tga";
					}
				}
			}
		}
	}

}
