<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>14</LangVersion>
        <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
        <AssemblyName>Oxide.Ext.UiFramework</AssemblyName>
        <RootNamespace>Oxide.Ext.UiFramework</RootNamespace>
        <Configurations>Debug;Release;Trace Leaks</Configurations>
        <Platforms>Unit Tests;UiFramework;Benchmarks</Platforms>
        <AssemblyVersion>$(VERSION)</AssemblyVersion>
        <FileVersion>$(VERSION)</FileVersion>
        <TargetFrameworks>net48;netstandard2.1;netcoreapp3.0</TargetFrameworks>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>.\Generated</CompilerGeneratedFilesOutputPath>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>
    
    <ItemGroup>
      <Reference Include="0Harmony">
        <HintPath>..\references\Rust\0Harmony.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp">
        <HintPath>..\references\Rust\Assembly-CSharp.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp-firstpass">
        <HintPath>..\references\Rust\Assembly-CSharp-firstpass.dll</HintPath>
      </Reference>
      <Reference Include="Facepunch.Console">
        <HintPath>..\references\Rust\Facepunch.Console.dll</HintPath>
      </Reference>
      <Reference Include="Facepunch.Network">
        <HintPath>..\references\Rust\Facepunch.Network.dll</HintPath>
      </Reference>
      <Reference Include="Facepunch.Sqlite">
        <HintPath>..\references\Rust\Facepunch.Sqlite.dll</HintPath>
      </Reference>
      <Reference Include="Facepunch.System">
        <HintPath>..\references\Rust\Facepunch.System.dll</HintPath>
      </Reference>
      <Reference Include="Facepunch.UnityEngine">
        <HintPath>..\references\Rust\Facepunch.UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="Ionic.Zip.Reduced">
        <HintPath>..\references\Rust\Ionic.Zip.Reduced.dll</HintPath>
      </Reference>
      <Reference Include="mscorlib">
        <HintPath>..\references\Rust\mscorlib.dll</HintPath>
      </Reference>
      <Reference Include="netstandard" Condition="'$(TargetFramework)' == 'net48'">
        <HintPath>..\references\Rust\netstandard.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.Core">
        <HintPath>..\references\Rust\Oxide.Core.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.CSharp">
        <HintPath>..\references\Rust\Oxide.CSharp.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.References">
        <HintPath>..\references\Rust\Oxide.References.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.Rust">
        <HintPath>..\references\Rust\Oxide.Rust.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.SQLite">
        <HintPath>..\references\Rust\Oxide.SQLite.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.Unity">
        <HintPath>..\references\Rust\Oxide.Unity.dll</HintPath>
      </Reference>
      <Reference Include="Rust.Data">
        <HintPath>..\references\Rust\Rust.Data.dll</HintPath>
      </Reference>
      <Reference Include="Rust.Global">
        <HintPath>..\references\Rust\Rust.Global.dll</HintPath>
      </Reference>
      <Reference Include="Rust.UI">
        <HintPath>..\references\Rust\Rust.UI.dll</HintPath>
      </Reference>
      <Reference Include="System">
        <HintPath>..\references\Rust\System.dll</HintPath>
      </Reference>
      <Reference Include="System.Core">
        <HintPath>..\references\Rust\System.Core.dll</HintPath>
      </Reference>
      <Reference Include="System.Drawing" Condition="'$(Platform)' != 'UiFramework'">
        <HintPath>..\references\Rust\System.Drawing.dll</HintPath>
      </Reference>
      <Reference Include="System.Net.Http">
        <HintPath>..\references\Rust\System.Net.Http.dll</HintPath>
      </Reference>
      <Reference Include="System.Runtime.CompilerServices.Unsafe">
        <HintPath>..\references\Rust\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
      </Reference>
      <Reference Include="System.Threading.Channels">
        <HintPath>..\references\Rust\System.Threading.Channels.dll</HintPath>
      </Reference>
      <Reference Include="System.Threading.Tasks.Extensions">
        <HintPath>..\references\Rust\System.Threading.Tasks.Extensions.dll</HintPath>
      </Reference>
      <Reference Include="UniTask">
        <HintPath>..\references\Rust\UniTask.dll</HintPath>
      </Reference>
      <Reference Include="UniTask.Linq">
        <HintPath>..\references\Rust\UniTask.Linq.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Burst">
        <HintPath>..\references\Rust\Unity.Burst.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Mathematics">
        <HintPath>..\references\Rust\Unity.Mathematics.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine">
        <HintPath>..\references\Rust\UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AssetBundleModule">
        <HintPath>..\references\Rust\UnityEngine.AssetBundleModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>..\references\Rust\UnityEngine.CoreModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ImageConversionModule">
        <HintPath>..\references\Rust\UnityEngine.ImageConversionModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextRenderingModule">
        <HintPath>..\references\Rust\UnityEngine.TextRenderingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UI">
        <HintPath>..\references\Rust\UnityEngine.UI.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestModule">
        <HintPath>..\references\Rust\UnityEngine.UnityWebRequestModule.dll</HintPath>
      </Reference>
    </ItemGroup>
    
    <ItemGroup>
      <Content Include="..\..\.gitattributes">
        <Link>.gitattributes</Link>
      </Content>
      <Content Include="..\..\.github\workflows\ci.yml">
        <Link>ci.yml</Link>
      </Content>
      <Content Include="..\..\.github\workflows\develop.yml">
        <Link>develop.yml</Link>
      </Content>
      <Content Include="..\..\.github\workflows\release.yml">
        <Link>release.yml</Link>
      </Content>
      <Content Include="..\..\.gitignore">
        <Link>.gitignore</Link>
      </Content>
      <Content Include="..\..\README.md">
        <Link>README.md</Link>
      </Content>
      <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs" />
      <Content Include="$(CompilerGeneratedFilesOutputPath)/Rust.UiFramework.SourceGenerators/**/*.cs" />
      <Compile Remove="Libraries\ImageStorage\Download\ThreadedImageDownloader.cs" />
      <Compile Remove="Threading\UiChannel\BaseUiChannel.cs" />
      <Compile Remove="Threading\UiChannel\IUiChannel.cs" />
      <Compile Remove="Threading\UiChannel\IUiChannelObject.cs" />
      <Compile Remove="Libraries\ImageStorage\Download\ImageDownloadQueue.cs" />
      <Compile Remove="Libraries\ImageStorage\Download\ImageDownloadRequest.cs" />
      <Compile Remove="Threading\UiChannel\BaseUniTaskChannel.cs" />
      <Compile Remove="Threading\UiChannel\IUniTaskChannelObject.cs" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="ErrorProne.NET.CoreAnalyzers" Version="0.1.2">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="ErrorProne.NET.Structs" Version="0.1.2">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="PolySharp" Version="1.16.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="System.Drawing.Common" Version="9.0.1" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Rust.UiFramework.Benchmarks</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Rust.UiFramework.UnitTests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Rust.UiFramework.SourceGenerators\Rust.UiFramework.SourceGenerators.csproj" 
                        OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <ItemGroup>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\GenerateJsonWriterAttribute.cs">
        <Link>Attributes\GenerateJsonWriterAttribute.cs</Link>
      </Compile>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\GenerateRegisterCommandsAttribute.cs">
        <Link>Attributes\GenerateRegisterCommandsAttribute.cs</Link>
      </Compile>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\PropertyNameAttribute.cs">
        <Link>Attributes\PropertyNameAttribute.cs</Link>
      </Compile>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\PropertyTargetAttribute.cs">
        <Link>Attributes\PropertyTargetAttribute.cs</Link>
      </Compile>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\GenerateBuilderMethodsAttribute.cs">
        <Link>Attributes\GenerateBuilderMethodsAttribute.cs</Link>
      </Compile>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\GenerateComponentAttribute.cs">
        <Link>Attributes\GenerateComponentAttribute.cs</Link>
      </Compile>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\GenerateUiElementAttribute.cs">
        <Link>Attributes\GenerateUiElementAttribute.cs</Link>
      </Compile>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\SkipBuilderAttribute.cs">
        <Link>Attributes\SkipBuilderAttribute.cs</Link>
      </Compile>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\TrackedAttribute.cs">
        <Link>Attributes\TrackedAttribute.cs</Link>
      </Compile>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\TrackedDefaultsAttribute.cs">
        <Link>Attributes\TrackedDefaultsAttribute.cs</Link>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Generated\Rust.UiFramework.SourceGenerators\" />
    </ItemGroup>

    <PropertyGroup>
        <MSBuildWarningsAsMessages>
            MSB3277;
        </MSBuildWarningsAsMessages>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|Benchmarks' ">
      <DefineConstants>TRACE;DEBUG;BENCHMARKS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|UiFramework' ">
      <DefineConstants>TRACE;DEBUG;SERVER</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|Unit Tests' ">
      <DefineConstants>TRACE;DEBUG;UNIT_TESTS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|Benchmarks' ">
      <DefineConstants>TRACE;BENCHMARKS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|UiFramework' ">
      <DefineConstants>TRACE;SERVER</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|Unit Tests' ">
      <DefineConstants>TRACE;UNIT_TESTS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Trace Leaks|Benchmarks' ">
      <DefineConstants>TRACE;DEBUG;TRACE_LEAKS;BENCHMARKS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Trace Leaks|UiFramework' ">
      <DefineConstants>TRACE;DEBUG;TRACE_LEAKS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Trace Leaks|Unit Tests' ">
      <DefineConstants>TRACE;DEBUG;TRACE_LEAKS;UNIT_TESTS</DefineConstants>
    </PropertyGroup>


    <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(GITHUB_ACTIONS)' != 'true'">
      <Exec Command="if '$(TargetFramework)' == 'net48' copy /Y &quot;$(TargetDir)$(TargetName).dll&quot; &quot;D:\Servers\Full\Rust-Main\steamapps\common\rust_dedicated\RustDedicated_Data\Managed&quot;" />
      <Exec Command="if '$(TargetFramework)' == 'net48' copy /Y &quot;$(TargetDir)$(TargetName).dll&quot; &quot;D:\Servers\Full\Rust-Staging\steamapps\common\rust_dedicated\RustDedicated_Data\Managed&quot;" />
    </Target>

</Project>
