<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>14</LangVersion>
        <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
        <AssemblyName>Oxide.Ext.UiFramework</AssemblyName>
        <RootNamespace>Oxide.Ext.UiFramework</RootNamespace>
        <Configurations>Debug;Release</Configurations>
        <Platforms>Unit Tests;UiFramework;Benchmarks</Platforms>
        <AssemblyVersion>$(VERSION)</AssemblyVersion>
        <FileVersion>$(VERSION)</FileVersion>
        <TargetFrameworks>net48;netstandard2.1;netcoreapp3.0</TargetFrameworks>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>.\Generated</CompilerGeneratedFilesOutputPath>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>
    
    <ItemGroup>
      <Reference Include="0Harmony">
        <HintPath>..\References\0Harmony.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp">
        <HintPath>..\References\Assembly-CSharp.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp-firstpass">
        <HintPath>..\References\Assembly-CSharp-firstpass.dll</HintPath>
      </Reference>
      <Reference Include="Facepunch.Console">
        <HintPath>..\References\Facepunch.Console.dll</HintPath>
      </Reference>
      <Reference Include="Facepunch.Network">
        <HintPath>..\References\Facepunch.Network.dll</HintPath>
      </Reference>
      <Reference Include="Facepunch.Sqlite">
        <HintPath>..\references\Facepunch.Sqlite.dll</HintPath>
      </Reference>
      <Reference Include="Facepunch.System">
        <HintPath>..\References\Facepunch.System.dll</HintPath>
      </Reference>
      <Reference Include="Facepunch.UnityEngine">
        <HintPath>..\References\Facepunch.UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="Ionic.Zip.Reduced">
        <HintPath>..\references\Ionic.Zip.Reduced.dll</HintPath>
      </Reference>
      <Reference Include="mscorlib">
        <HintPath>..\References\mscorlib.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.Core">
        <HintPath>..\References\Oxide.Core.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.CSharp">
        <HintPath>..\References\Oxide.CSharp.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.References">
        <HintPath>..\References\Oxide.References.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.Rust">
        <HintPath>..\References\Oxide.Rust.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.SQLite">
        <HintPath>..\References\Oxide.SQLite.dll</HintPath>
      </Reference>
      <Reference Include="Oxide.Unity">
        <HintPath>..\References\Oxide.Unity.dll</HintPath>
      </Reference>
      <Reference Include="Rust.Data">
        <HintPath>..\References\Rust.Data.dll</HintPath>
      </Reference>
      <Reference Include="Rust.Global">
        <HintPath>..\References\Rust.Global.dll</HintPath>
      </Reference>
      <Reference Include="Rust.UI">
        <HintPath>..\references\Rust.UI.dll</HintPath>
      </Reference>
      <Reference Include="System">
        <HintPath>..\references\System.dll</HintPath>
      </Reference>
      <Reference Include="System.Core">
        <HintPath>..\references\System.Core.dll</HintPath>
      </Reference>
      <Reference Include="System.Net.Http">
        <HintPath>..\references\System.Net.Http.dll</HintPath>
      </Reference>
      <Reference Include="System.Runtime.CompilerServices.Unsafe">
        <HintPath>..\references\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
      </Reference>
      <Reference Include="System.Threading.Channels">
        <HintPath>..\references\System.Threading.Channels.dll</HintPath>
      </Reference>
      <Reference Include="System.Threading.Tasks.Extensions">
        <HintPath>..\references\System.Threading.Tasks.Extensions.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine">
        <HintPath>..\References\UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>..\References\UnityEngine.CoreModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextRenderingModule">
        <HintPath>..\References\UnityEngine.TextRenderingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UI">
        <HintPath>..\References\UnityEngine.UI.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestModule">
        <HintPath>..\references\UnityEngine.UnityWebRequestModule.dll</HintPath>
      </Reference>
    </ItemGroup>
    
    <ItemGroup>
      <Content Include="..\..\.gitattributes">
        <Link>.gitattributes</Link>
      </Content>
      <Content Include="..\..\.github\workflows\ci.yml">
        <Link>ci.yml</Link>
      </Content>
      <Content Include="..\..\.github\workflows\develop.yml">
        <Link>develop.yml</Link>
      </Content>
      <Content Include="..\..\.github\workflows\release.yml">
        <Link>release.yml</Link>
      </Content>
      <Content Include="..\..\.gitignore">
        <Link>.gitignore</Link>
      </Content>
      <Content Include="..\..\README.md">
        <Link>README.md</Link>
      </Content>
      <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs" />
      <Content Include="$(CompilerGeneratedFilesOutputPath)/Rust.UiFramework.SourceGenerators/**/*.cs" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="ErrorProne.NET.CoreAnalyzers" Version="0.1.2">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="ErrorProne.NET.Structs" Version="0.1.2">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="PolySharp" Version="1.15.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="System.Drawing.Common" Version="9.0.1" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Rust.UiFramework.Benchmarks</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Rust.UiFramework.UnitTests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Rust.UiFramework.SourceGenerators\Rust.UiFramework.SourceGenerators.csproj" 
                        OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <ItemGroup>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\GenerateJsonWriterAttribute.cs">
        <Link>Attributes\GenerateJsonWriterAttribute.cs</Link>
      </Compile>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\GenerateRegisterCommandsAttribute.cs">
        <Link>Attributes\GenerateRegisterCommandsAttribute.cs</Link>
      </Compile>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\PropertyNameAttribute.cs">
        <Link>Attributes\PropertyNameAttribute.cs</Link>
      </Compile>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\PropertyTargetAttribute.cs">
        <Link>Attributes\PropertyTargetAttribute.cs</Link>
      </Compile>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\GenerateBuilderMethodsAttribute.cs">
        <Link>Attributes\GenerateBuilderMethodsAttribute.cs</Link>
      </Compile>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\GenerateComponentAttribute.cs">
        <Link>Attributes\GenerateComponentAttribute.cs</Link>
      </Compile>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\GenerateUiElementAttribute.cs">
        <Link>Attributes\GenerateUiElementAttribute.cs</Link>
      </Compile>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\SkipBuilderAttribute.cs">
        <Link>Attributes\SkipBuilderAttribute.cs</Link>
      </Compile>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\TrackedAttribute.cs">
        <Link>Attributes\TrackedAttribute.cs</Link>
      </Compile>
      <Compile Include="..\Rust.UiFramework.SourceGenerators\Attributes\TrackedDefaultsAttribute.cs">
        <Link>Attributes\TrackedDefaultsAttribute.cs</Link>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Generated\Rust.UiFramework.SourceGenerators\" />
    </ItemGroup>

    <PropertyGroup>
        <MSBuildWarningsAsMessages>
            MSB3277;
        </MSBuildWarningsAsMessages>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|Benchmarks' ">
      <DefineConstants>TRACE;DEBUG;BENCHMARKS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|UiFramework' ">
      <DefineConstants>TRACE;DEBUG</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|Unit Tests' ">
      <DefineConstants>TRACE;DEBUG;UNIT_TESTS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|Benchmarks' ">
      <DefineConstants>TRACE;BENCHMARKS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|UiFramework' ">
      <DefineConstants>TRACE;SERVER</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|Unit Tests' ">
      <DefineConstants>TRACE;UNIT_TESTS</DefineConstants>
    </PropertyGroup>

</Project>
